/* ============================================================
   WUTHERING WAVES — RESONATOR DATA
   Converted to the shared CharacterCard field shape.
   `element` holds the attribute key used for theme lookup.
   ============================================================ */

export const WUWA_VERSION = "3.5";

export const ATTRIBUTE_THEME = {
  glacio:  { color: "#9fd8e8", glow: "rgba(159,216,232,0.18)", label: "Glacio" },
  fusion:  { color: "#e8875d", glow: "rgba(232,135,93,0.18)",  label: "Fusion" },
  electro: { color: "#c58ae0", glow: "rgba(197,138,224,0.18)", label: "Electro" },
  aero:    { color: "#7fd4b5", glow: "rgba(127,212,181,0.18)", label: "Aero" },
  spectro: { color: "#e8d27f", glow: "rgba(232,210,127,0.18)", label: "Spectro" },
  havoc:   { color: "#d17a9e", glow: "rgba(209,122,158,0.18)", label: "Havoc" },
};

export const RESONATORS = [
  {
    id: "xuanling",
    name: "Yangyang: Xuanling",
    epithet: "Votary of the Voice",
    element: "havoc",
    role: "Main DPS",
    weaponType: "Sword",
    set: "5pc Song of Feathered Trace · Thousand-Puppet Pavilion main",
    setAlt: "5pc Havoc Eclipse · 5pc Thread of Severed Fate",
    weapon: "Azure Oath",
    weaponAlt: "Emerald Sentence · Red Spring · Emerald of Genesis · Lumingloss",
    talents: "Forte Circuit >> Liberation > Normal > Skill = Intro",
    stats: [
      { id: "4cost-main", label: "4-Cost Main Stat", target: "CRIT DMG (her set + signature already stack CRIT Rate)" },
      { id: "3cost-main", label: "3-Cost Main Stats", target: "Havoc DMG% x2" },
      { id: "1cost-main", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "~50% sheet → 65-70% in combat (set Feather grants +20%)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "220-250% (keep ~1:2 ratio vs CRIT Rate)" },
      { id: "total-atk", label: "Total ATK", target: "1900-2200 fully buffed" },
      { id: "energy-regen", label: "Energy Regen", target: "115-120% so Liberation is up every rotation" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate/DMG > Heavy Attack DMG > ATK% > ER" },
    ],
    note: "Do not default to CRIT Rate on the 4-cost: Song of Feathered Trace's Feather buff (+20% CRIT Rate on inflicting Havoc Bane) plus Azure Oath already push her rate high, so CRIT DMG avoids overcapping. And because Liberation is ~37% of her damage, dropping below ~115% Energy Regen quietly wrecks her rotation.",
    deep: {
      lore: "Second daughter of the famed Xuanling musical dynasty of Mingting and younger sister of Suisui, Yangyang bears the rare gift of communing with the Streams — the \"Votary of the Voice.\" Once an Outrider of Jinzhou's Midnight Rangers, she now stands as acting Xuan Watcher at Xuanfang Hold, her blade raised only to protect. She is Wuthering Waves' first SP Resonator, a Havoc-attuned reimagining of the original Aero outrider.",
      kit: [
        "Resonance Skill — Sword Stance Flow: cycles between Azure and Feather Sword Stances; empowered stance-switch casts deal Havoc DMG counted as Heavy Attack DMG and refill her Melody gauge (max 100).",
        "Both stances' Basic Attack chains apply Havoc Bane on their finishers; Havoc Bane in turn feeds her self-buffs — Streaming Storm (+160% CRIT DMG) and Feathered Oath (up to +150%) reward staying in Feather Sword Stance.",
        "Resonance Liberation — Hush of a Thousand Voices: spends all Melody on a massive Havoc Heavy Attack hit, instantly maxes Havoc Bane stacks on everything hit, and grants Voice upon Voice so the next Sword Stance Flow summons Shadow of Xuanling for a bonus Heavy Attack hit.",
        "Outro — As the Wind Wills: grants Tonal Switch to teammates for 20s, amplifying their Havoc DMG by 20% the next time they inflict Havoc Bane.",
        "Damage split: Forte Circuit ~58%, Liberation ~37%, Basic ~4%, Intro ~1% — nearly everything she does snapshots as Heavy Attack DMG, so Heavy Attack buffers multiply her whole kit.",
      ],
      tips: [
        "Core rotation: Intro (Skybound Feather) → Liberation → Sword Stance Flow: Feather → Feather-stance Heavy → Havoc in Bloom I-III basic chain → Echo (Thousand-Puppet Pavilion) → Outro; keep Havoc Bane active the entire time.",
        "Run the 4-3-3-1-1 layout: CRIT DMG 4-cost, double Havoc DMG% 3-costs, ATK% 1-costs; roll substats toward CRIT first, then Heavy Attack DMG.",
        "Thousand-Puppet Pavilion's Blades of Thousand Memories detonate when Havoc Bane is inflicted — cast the Echo before her Bane-applying finishers, not after.",
        "On Emerald of Genesis (best F2P pick), her frequent stance-switch Skill casts keep the ATK stacks up and the extra Energy Regen loosens her ER substat requirement.",
      ],
      synergies: [
        { id: "mortefi", why: "Nearly everything she does snapshots as Heavy Attack DMG, so Mortefi's 38% Heavy Attack Deepen Outro amplifies her whole kit — the classic 4-star pairing for Heavy-Attack carries." },
        { id: "verina", why: "Universal amplifier + healer: her long-duration All-Type Deepen and sustain cover Xuanling's field-hungry Melody loop without competing for rotation time." },
        { id: "shorekeeper", why: "Universal sustain slot: continuous healing plus CRIT buffs from her Liberation field, adding a damage-amp layer without competing for field time." },
      ],
    },
  },
  {
    id: "luuk-herssen",
    name: "Luuk Herssen",
    epithet: "Phase Transition",
    element: "spectro",
    role: "Main DPS",
    weaponType: "Gauntlets",
    set: "5pc Rite of Gilded Revelation · Twin Nova: Nebulous Cannon main",
    setAlt: "5pc Celestial Light",
    weapon: "Daybreaker's Spine",
    weaponAlt: "Pulsation Bracer · Abyss Surges · Blazing Justice · Celestial Spiral (4★)",
    talents: "Skill >> Liberation > Forte Circuit > Basic Attack > Intro",
    stats: [
      { id: "cost4-main", label: "4-Cost Main Stat", target: "CRIT Rate (or CRIT DMG — keep the 1:2 ratio)" },
      { id: "cost3-main", label: "3-Cost Main Stats", target: "Spectro DMG% x2" },
      { id: "cost1-main", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "65–70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "230–250% (~240% ideal)" },
      { id: "total-atk", label: "Total ATK", target: "~2,000+" },
      { id: "energy-regen", label: "Energy Regen", target: "≥120%" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate = CRIT DMG > ATK% > Basic Attack DMG% > Flat ATK" },
    ],
    note: "His Enhanced Skill loop (Aureole of Execution) is tagged as Basic Attack DMG, so the Rite of Gilded Revelation's 40% Basic ATK line and Basic Attack DMG% substats all apply — Celestial Light is only a stopgap that gives up that entire bonus. And don't skimp on Energy Regen: below ~120% his 3-stack Liberation finisher slips out of the rotation and the whole loop deflates.",
    deep: {
      lore: "Head physician of the Resonator Nursing Unit at Startorch Academy — attending doctor and mental-health counselor by day, a man with a conspicuously mysterious past by every other measure. Released in Version 3.1 as the premier Tune Strain DPS, he fights the way he practices medicine: precise, airborne, and always three moves ahead of the diagnosis.",
      kit: [
        "Resonance Skill: cycles through three Enhanced Resonance Skill forms; landing the 4th Basic Attack stage or 3rd Aerial Attack stage replaces his Skill with the Aureole of Execution — the core of his relentless mid-air loop.",
        "Forte Circuit: each Aureole of Execution stacks 'Endnotes on the Endgame' (max 3); every stack raises the DMG multiplier of his Liberation by 25%.",
        "Resonance Liberation (Rewritten in Winter's Margins): the big Spectro finisher — cast it at 3 Endnote stacks each rotation, which is why the ≥120% ER floor matters.",
        "Tune Strain engine: inflicts Tune Strain – Shifting/Interfered on hit, gaining Basic Attack DMG Amplification and DEF-ignore; teammates' Tune Break boosts amplify him further.",
        "Where the damage lives: the Basic-Attack-tagged Aureole of Execution loop makes up the bulk, capped off by the stacked Liberation nuke; his Intro/Outro contribution is minimal — he's a selfish on-fielder.",
      ],
      tips: [
        "Rotation in one sentence: finish the basic/aerial chain to unlock Aureole of Execution, cast three Enhanced Skills to stack Endnotes x3, then drop Liberation.",
        "Swap him in right after Mornye's Outro — her 25% teamwide DMG Amplification lasts 30s, covering his entire field phase.",
        "Stay airborne: his enhanced kit is built around aerial pressure; grounded play wastes his Aerial Attack stage triggers.",
        "F2P weapon path: Pulsation Bracer (3.0 standard 5★) is a near-mechanical copy of his signature and is recommended for most players; 4★ Celestial Spiral only as a stopgap.",
      ],
      synergies: [
        { id: "shorekeeper", why: "Universal premium support: Stellarealm crit feed, healing, and concerto support slot cleanly under his relentless mid-air Skill loop." },
        { id: "lynae", why: "Premier Tune Strain sub-DPS: adds Tune Strain stack generation and extra Tune Strain buffs off-field, raising the team's max stack potential and Tune Break efficiency." },
        { id: "shorekeeper", why: "Plug-and-play sustain with a teamwide 15% DMG Amplified Outro — the safe third slot when Mornye/Lynae comps aren't available." },
      ],
    },
  },
  {
    id: "lynae",
    name: "Lynae",
    epithet: "Radiant Spectrum",
    element: "spectro",
    role: "Sub-DPS / Universal Buffer",
    weaponType: "Pistols",
    set: "5pc Pact of Neonlight Leap · Hyvatia main",
    setAlt: "5pc Rite of Gilded Revelation · 5pc Moonlit Clouds",
    weapon: "Spectrum Blaster",
    weaponAlt: "Phasic Homogenizer · Static Mist · Relativistic Jet · Solar Flame",
    talents: "Forte >> Liberation > Normal > Skill > Intro",
    stats: [
      { id: "main-4c", label: "4-Cost Main Stat", target: "CRIT Rate (or CRIT DMG)" },
      { id: "main-3c", label: "3-Cost Main Stats", target: "Spectro DMG% x2 (one ER% if rotations feel tight)" },
      { id: "main-1c", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "60-70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "200-250%" },
      { id: "total-atk", label: "Total ATK", target: "2,000-2,200" },
      { id: "energy-regen", label: "Energy Regen", target: "120-125%" },
      { id: "substats", label: "Substat Priority", target: "CRIT > Basic Attack DMG > ATK% > ER" },
    ],
    note: "Do not overinvest in Energy Regen — she only needs ~120-125% to keep Prismatic Overblast cycling, and her buffs come from her kit, not her stats. Every point of ER past that (or an ER 3-cost main stat by default) is a common mistake that tanks her very real personal Basic Attack damage, which wants CRIT and ATK like a DPS.",
    altBuilds: [
      {
        id: "lynae-dps",
        label: "Personal DPS (Gilded Revelation)",
        role: "On-field Basic Attack Sub-DPS",
        set: "5pc Rite of Gilded Revelation",
        setAlt: "5pc Pact of Neonlight Leap",
        weapon: "Spectrum Blaster",
        weaponAlt: "Relativistic Jet · Solar Flame",
        talents: "Forte >> Normal > Liberation > Skill > Intro",
        stats: [
          { id: "dps-main-4c", label: "4-Cost Main Stat", target: "CRIT Rate or CRIT DMG (balance to ~1:2)" },
          { id: "dps-main-3c", label: "3-Cost Main Stats", target: "Spectro DMG% x2" },
          { id: "dps-main-1c", label: "1-Cost Main Stats", target: "ATK% x2" },
          { id: "dps-crit-rate", label: "CRIT Rate", target: "65-80%" },
          { id: "dps-crit-dmg", label: "CRIT DMG", target: "250-280%" },
          { id: "dps-total-atk", label: "Total ATK", target: "2,000+" },
          { id: "dps-energy-regen", label: "Energy Regen", target: "~110-120% (bare minimum)" },
          { id: "dps-substats", label: "Substat Priority", target: "CRIT > Basic Attack DMG > ATK%" },
        ],
        note: "Gilded Revelation stacks Spectro DMG through Basic Attacks and grants +40% Basic Attack DMG on Liberation cast, maximizing Kaleidoscopic Parade — but you give up the Neonlight Leap Outro ATK buff, so run this only when Lynae herself is the damage plan.",
      },
    ],
    deep: {
      lore: "Born a mercenary in the New Federation's Lawless Zone, she was hired to eliminate a Fractsidus operative named Lynae — and instead took the dying woman's Startorch Academy acceptance letter, faked her own death, and walked into a new life. The cold professional who once called anything that wasn't a weapon \"dead weight\" found friends, color, and belonging at the academy in Lahai-Roi, eventually re-enrolling under her own terms while keeping the name she had grown to love.",
      kit: [
        "Forte Circuit — Optical Sampling / Kaleidoscopic Parade: she builds Overflow in her default Optical Sampling stage, then Basic Attack: Spark Collision launches Kaleidoscopic Parade, an empowered pistol-barrage state where the bulk of her personal Spectro damage lives (it all counts as Basic Attack DMG).",
        "Resonance Skill — Lynae-Style Palettes / Additive Color (shared cooldown): quick Spectro pokes that feed Overflow and keep her rotation moving during quick swaps.",
        "Resonance Liberation — Prismatic Overblast: big Spectro burst that grants the WHOLE team +24% All DMG for 30s, and unlocks the follow-up Basic Attack \"To a Vivid Tomorrow!\", one of her hardest hits.",
        "Outro — Let's Hit the Road!: the next Resonator gets 15% All DMG Amplification and 25% Resonance Liberation DMG Amplification for 14s — element-agnostic, so she slots behind almost any main DPS.",
        "Her Tune Break / Tune Shifting debuff mechanic scales her team buffing (and her signature weapon's team DMG stacks), making her a rare universal amplifier who still posts serious sub-DPS numbers.",
        "With 5pc Pact of Neonlight Leap + Hyvatia, each Outro also hands the incoming DPS up to +30% ATK and +10% All-Attribute DMG — the swap itself becomes a damage steroid.",
      ],
      tips: [
        "Standard loop (~25s): Intro > Skill/Basics to build Overflow > Liberation > Kaleidoscopic Parade basic string > Outro into your main DPS while her 30s team buff keeps running.",
        "Always exit via Outro, not a raw swap — the 15%/25% amps, Neonlight Leap ATK buff, and Hyvatia bonus are all tied to the Outro cast.",
        "She is complete at S0 with one copy; Static Mist or Phasic Homogenizer get her close to signature performance, so she is genuinely F2P-friendly.",
        "Farm Pact of Neonlight Leap for team play; only run Rite of Gilded Revelation if you deliberately want a selfish personal-damage Lynae.",
      ],
      synergies: [
        { id: "xuanling", why: "Her Resonance Liberation DMG Amplification lands squarely on Yangyang: Xuanling's Melody-dump Liberation nukes (~37% of her damage), stacking with the element-free All-DMG amp." },
        { id: "luuk-herssen", why: "Tune Strain core partner: Lynae's stack generation and amps raise Luuk's Tune Break ceiling — the era-defining pairing both kits were tuned around." },
        { id: "shorekeeper", why: "Shorekeeper's healing and CRIT buffs stack cleanly with Lynae's ATK/DMG amps, forming the classic amp-plus-sustain backline behind any hypercarry." },
      ],
    },
  },
  {
    id: "shorekeeper",
    name: "Shorekeeper",
    epithet: "Guardian of the Black Shores",
    element: "spectro",
    role: "Support / Healer",
    weaponType: "Rectifier",
    set: "5pc Rejuvenating Glow · Fallacy of No Return main",
    setAlt: "5pc Moonlit Clouds · 2pc Rejuvenating Glow + 2pc Moonlit Clouds",
    weapon: "Stellar Symphony",
    weaponAlt: "Call of the Abyss (F2P craftable) · Variation (gacha 4★)",
    talents: "Skill = Intro > Liberation > Forte >> Basic",
    stats: [
      { id: "main-4c", label: "4-Cost Main Stat", target: "HP% (her own Crit does nothing — skip CRIT mains)" },
      { id: "main-3c", label: "3-Cost Main Stats", target: "Energy Regen% ×2 (swap one to HP% if ER-capped via Stellar Symphony)" },
      { id: "main-1c", label: "1-Cost Main Stats", target: "HP% ×2" },
      { id: "er-target", label: "Energy Regen", target: "250% total (230% is enough with Fallacy of No Return's +10% + her inherent +10%)" },
      { id: "hp-target", label: "Total HP", target: "~30,000+ (scales all her healing)" },
      { id: "crit-targets", label: "CRIT Rate / CRIT DMG", target: "Not needed — she grants the team up to +12.5% CR / +25% CD off her ER instead" },
      { id: "substats", label: "Substat Priority", target: "Energy Regen% > HP% > Flat HP > Healing Bonus" },
    ],
    note: "Do NOT build her with Crit or ATK: her party-wide Crit Rate/Crit DMG buff scales purely off her Energy Regen, capping at exactly 250% ER (12.5% CR / 25% CD) — anything past 250% is wasted, and anything under it is leaving free team Crit on the table. With the Fallacy of No Return echo and her inherent skill contributing ~20% ER, gearing to ~230% on the stat sheet is sufficient.",
    deep: {
      lore: "An enigmatic being who awoke in the Black Shores and became its guardian, the Shorekeeper is a constructed vessel who taught herself what it means to feel across countless cycles of watching over the Rover. Ageless and star-bound, she tends the boundary between dream and sea, her butterflies carrying fragments of memory across Solaris-3's tides.",
      kit: [
        "Resonance Skill (Chaos Theory): instantly heals the whole team and summons 5 Dim Star Butterflies that home in on enemies for Spectro DMG — her heals all scale off max HP.",
        "Resonance Liberation (End Loop): generates the Stellarealm, a large field that periodically heals active allies and grants Crit Rate/Crit DMG that scales with her Energy Regen — up to +12.5% CR / +25% CD at 250% ER.",
        "Forte Circuit: allied Intro Skills cast inside the field upgrade it twice (Inner → Supernal Stellarealm), boosting the Crit buffs and triggering her butterfly-form burst heal.",
        "Outro (Binary Butterfly): 15% All-Type DMG Amplification for the entire team for 30s that is NOT lost on swapping — usable by any DPS of any attribute.",
        "Her personal damage is negligible; 100% of her value is healing, ER-scaled Crit buffs, the all-type amp, and carrying the Rejuvenating Glow 15% team ATK buff.",
      ],
      tips: [
        "Hit the 250% ER breakpoint before anything else — Call of the Abyss (free craftable) or Variation (gacha 4★) plus the Fallacy of No Return echo gets you there comfortably without her signature weapon.",
        "Always Intro your DPS inside her Stellarealm: two Intro casts upgrade it to Supernal Stellarealm for the full Crit buff; a field that never gets upgraded is half a Liberation.",
        "Keep her rotation short: Intro → Skill → Echo → Liberation → Outro, then get your carry back on field; her buffs and Rejuvenating Glow ATK boost persist while she is off-field.",
        "She is the game's best Rejuvenating Glow carrier — her constant passive healing keeps the set's 15% team ATK buff at near-100% uptime.",
      ],
      synergies: [
        { id: "encore", why: "Her healing holds Encore above the 70% HP threshold that gates Encore's +10% Cosmos Rave bonus, while the Stellarealm crit feed scales the Rave basics directly." },
        { id: "xuanling", why: "Field-hungry Havoc hypercarry — Shorekeeper does her buff/heal routine in seconds and hands the field back with crit support that covers Xuanling's whole Melody loop." },
        { id: "lingyang", why: "Crit-hungry Glacio Liberation carry — Shorekeeper's +12.5% CR / +25% CD closes his crit budget while her sustain covers his long transformed windows." },
      ],
    },
  },
  {
    id: "lucy",
    name: "Lucy",
    epithet: "Netrunner of Night City",
    element: "spectro",
    role: "Heavy Attack Spectro Main DPS",
    weaponType: "Pistols",
    set: "1pc Shadow of Shattered Dreams + double 2pc Spectro DMG (e.g. Celestial Light + Rite of Gilded Revelation) · Reminiscence: Nightmare Adam Smasher main",
    setAlt: "5pc Celestial Light · 5pc Eternal Radiance",
    weapon: "Spectral Trigger",
    weaponAlt: "The Last Dance · Phasic Homogenizer · Static Mist · Relativistic Jet",
    talents: "Liberation >> Normal Attack > Forte > Skill (Intro last)",
    stats: [
      { id: "main-4c", label: "4-cost main stat", target: "CRIT Rate (CRIT DMG if ratio is already high)" },
      { id: "main-3c", label: "3-cost main stats", target: "Spectro DMG % x2" },
      { id: "main-1c", label: "1-cost main stats", target: "ATK % x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "65-70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "230-250%" },
      { id: "total-atk", label: "Total ATK", target: "2,200+" },
      { id: "energy-regen", label: "Energy Regen", target: "~110-120% (one Liberation per rotation)" },
      { id: "substats", label: "Substat priority", target: "CRIT Rate/DMG > Heavy Attack DMG > ATK% > flat ATK" },
    ],
    note: "Her BiS echo build is a 1+2+2 hybrid, not a 5-piece set: a single Adam Smasher activates Shadow of Shattered Dreams' +35% Heavy Attack DMG (via her constant Hack - Shifting triggers), and the other four slots run two separate 2pc Spectro DMG sets — forcing a full 5-piece is a damage loss. Also never cast Heavy Attack - Multi-threading without an SQL stack, or she loses 20% of current HP instead of gaining the +100% multiplier.",
    deep: {
      lore: "Lucyna Kushinada — the quiet, guarded netrunner of Cyberpunk: Edgerunners — grew up under Arasaka's control before escaping to survive in Night City, forever chasing her dream of the moon. She crosses into Solaris-3 as a Spectro Mutant Resonator in the WuWa x Edgerunners collab, bringing her deep-dive hacking arts and her bond with Rebecca along with her.",
      kit: [
        "Resonance Skill: Payload / Pulse Interference (plus Basic Attacks) build TCP; Pulse Interference grants Digital Handshake for passive TCP gain. At full TCP the Skill becomes Deadlock, entering Algorithm Compaction: +65% Spectro DMG for the window plus an SQL stack.",
        "Forte Circuit: in Algorithm Compaction her attacks upgrade to Thread Shredding / Single Threading; hits build Root Access, and at full stacks Heavy Attack Single Threading becomes Dual Threading, chaining into Multi-threading — her single biggest hit, +100% multiplier when it consumes SQL (but -20% current HP if cast without SQL).",
        "Hack mechanic: she constantly applies Hack - Shifting / Data Crash (Spectro Hack DMG that ticks and Stagnates the enemy for 0.5s when it attacks) — this is what keeps the Shadow of Shattered Dreams +35% Heavy ATK DMG bonus live.",
        "Resonance Liberation: Netrunner upgrades to Old Net Deep Dive after Multi-threading, with a greatly increased Override multiplier — roughly 47% of her damage lives here, so always cast it at the end of the enhanced window.",
        "Intro: Outdated Hallucination enhances Involuntary Sharing on Rebecca and triggers her turret's Overload. Outro: 25% Basic Attack Deepen (14s) plus team-wide Countermeasure Program (25s): +20% All-DMG Deepen when the active character applies Hack - Shifting, and 30% damage reduction with a 1s attacker pause when allies are hit.",
      ],
      tips: [
        "Core rotation: Intro > Echo > Basics > Payload > Pulse Interference > Deadlock > Single Threading > Basic > Dual Threading > Multi-threading (with SQL) > Old Net Deep Dive > Outro.",
        "Watch the SQL icon before committing to Multi-threading — with SQL it gains +100% multiplier, without it she pays 20% of her current HP.",
        "~120% Energy Regen is enough for one Liberation per rotation; past that, every ER roll is a dead stat — dump rolls into CRIT and Heavy Attack DMG instead.",
        "Adam Smasher is effectively mandatory: it is the only Shadow of Shattered Dreams echo and its skill is tailor-made for her — do not slot a generic Spectro 4-cost in its place.",
      ],
      synergies: [
        { id: "rebecca", why: "Her collab partner and best support — Rebecca preps Hack states and Good Choom buff windows that Lucy spends during Algorithm Compaction, while Lucy's Intro overloads Rebecca's turret; the two kits are explicitly written to cross-buff each other." },
        { id: "baizhi", why: "Budget third slot for the Lucy/Rebecca duo: You'Pan's off-field healing keeps the field-time-hungry pair alive without interrupting their long on-field damage windows." },
        { id: "shorekeeper", why: "Top-end universal sustain alternative — her field's unconditional CRIT Rate/CRIT DMG boost scales Lucy's Heavy Attack burst with no mechanical trigger requirements (Verina's 15% All-DMG Deepen Outro is the F2P-friendly stand-in)." },
      ],
    },
  },
  {
    id: "rebecca",
    name: "Rebecca",
    epithet: "Trigger-Happy Edgerunner",
    element: "electro",
    role: "Quick-swap Electro burst sub-DPS / Heavy Attack amplifier",
    weaponType: "Pistols",
    set: "1pc Shadow of Shattered Dreams + 2pc Void Thunder + 2pc Reel of Spliced Memories · Reminiscence: Nightmare Adam Smasher main",
    setAlt: "5pc Void Thunder · 5pc Moonlit Clouds (outro-bot / ER fix)",
    weapon: "Skull Thrasher (signature)",
    weaponAlt: "Static Mist · Solar Flame (BP, best 4★) · Thunderbolt (budget)",
    talents: "Liberation >> Forte Circuit > Normal Attack > Skill > Intro",
    stats: [
      { id: "4cost-main", label: "4-Cost Main Stat", target: "CRIT Rate or CRIT DMG (Adam Smasher already grants +15% CRIT Rate — balance around it)" },
      { id: "3cost-main", label: "3-Cost Main Stats", target: "Electro DMG% x2 (one Energy Regen% if Liberation isn't up every rotation)" },
      { id: "1cost-main", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "65-70% (including the 15% from her main Echo)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "220-260%" },
      { id: "total-atk", label: "Total ATK", target: "~2,000+ (ATK scaler; stack ATK% after crit)" },
      { id: "energy-regen", label: "Energy Regen", target: "~125% — her Liberation is ~40% of her damage and must be up every rotation" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate/DMG > ER (until ~125%) > ATK% > Basic Attack DMG Bonus" },
    ],
    note: "Her BiS is an unusual 1+2+2 split (1pc Shadow of Shattered Dreams via Adam Smasher + two 2pc bonuses), not a 5pc set — don't farm a full 5pc for her. Her Outro amp ramps over time, so the incoming carry must remain on-field for the buff's 14s duration so Overlimit stacks (1 per 0.2s, 0.5% each) can climb to the full 35% — there is no positioning requirement relative to the turret — and she bricks rotations below ~125% Energy Regen.",
    altBuilds: [
      {
        id: "outro-bot",
        label: "Outro-Bot Support",
        role: "Pure buffer for a high-investment hypercarry",
        set: "5pc Moonlit Clouds",
        setAlt: "1pc Shadow of Shattered Dreams + 2pc Moonlit Clouds + 2pc Void Thunder",
        weapon: "Static Mist",
        weaponAlt: "Skull Thrasher · Solar Flame",
        talents: "Liberation > Forte Circuit > everything else (Intro last)",
        stats: [
          { id: "sup-4cost", label: "4-Cost Main Stat", target: "CRIT Rate (keeps her burst relevant while buffing)" },
          { id: "sup-3cost", label: "3-Cost Main Stats", target: "Energy Regen% + Electro DMG%" },
          { id: "sup-1cost", label: "1-Cost Main Stats", target: "ATK% x2" },
          { id: "sup-er", label: "Energy Regen", target: "140-150% — guarantee Liberation + Outro every rotation with zero field time" },
          { id: "sup-crit", label: "CRIT Rate / DMG", target: "~55% / 180%+ (whatever rolls come; buffs don't scale off crit)" },
        ],
        note: "Run this when a high-sequence main DPS carries the team: Moonlit Clouds' Outro ATK buff plus Static Mist's Outro 10% ATK stacks on her native 15%/35% amp — she just intros, dumps Liberation/Forte, Outros and leaves.",
      },
    ],
    deep: {
      lore: "The pint-sized, foul-mouthed gunslinger of Maine's crew from Cyberpunk: Edgerunners, Rebecca crashes into Solaris-3 through Somnoire's dream of Night City in Version 3.4's \"The Dream Not Dreamed\" collab story. All twin-pistol swagger and zero impulse control — \"C'mon, need to hit somethin'!\" — she was handed to every Rover free, the first giveaway 5-star limited Resonator in WuWa's history.",
      kit: [
        "Basic Attack gunplay that constantly swaps between two firing modes (Hunter and Iron Guts); her damage identity is Basic Attack DMG with very fast Concerto generation, making her a natural quick-swap unit.",
        "Forte Circuit: filling the gauge to 120 Fervor unlocks a 3-stage empowered sequence — 15 shots fired in sets of 5, ending in a big finisher blast that can (and should) be swap-cancelled.",
        "Resonance Liberation \"BOOM! Fireworks!\": she mounts a heavy machine gun and becomes a stationary auto-locking turret with heavy damage reduction — roughly 40% of her personal damage, hence the ~125% ER requirement.",
        "Outro (where the real value lives): amplifies All-Type DMG by 15% for the incoming Resonator and deploys a damage-dealing turret that ramps their Heavy Attack DMG Amplification up to 35% — a total ~50% amp for Heavy Attack carries like Lucy or Augusta.",
        "Hack-Shifting: an Edgerunners-exclusive mechanic shared only with Lucy; Lucy's kit upgrades Rebecca's turret while Rebecca preps Hack states for her.",
      ],
      tips: [
        "Get Energy Regen to ~125% BEFORE greeding crit substats — a missed Liberation costs more than any crit roll gains.",
        "Swap-cancel her Forte finisher blast: the Concerto and damage still land while your carry takes the field inside her Outro window.",
        "Use her Outro right before your carry's burst window and keep them on-field for the full 14s — Overlimit stacks build 1 per 0.2s (0.5% each) until the Heavy Attack amp reaches 35%; no need to hug the turret.",
        "She's free and needs no dupes: Static Mist or even Solar Flame (Battle Pass, CRIT Rate substat) makes her endgame-viable — Skull Thrasher is a luxury.",
      ],
      synergies: [
        { id: "lucy", why: "Best-in-slot duo via the collab-exclusive Hack-Shifting mechanic: Rebecca's ~50% All-Type + Heavy Attack amplification feeds Lucy's Heavy Attack burst, while Lucy debuffs enemies and upgrades Rebecca's turret." },
        { id: "xuanling", why: "Top in-roster Heavy Attack hypercarry and the best non-collab recipient of Rebecca's burst amp — Xuanling's long Melody windows soak the support while Rebecca contributes off-field Electro damage." },
        { id: "shorekeeper", why: "Preferred sustain for the field-hungry Edgerunners core — her buff routine takes seconds, and the Stellarealm crit feed covers both halves of the collab duo." },
      ],
    },
  },
  {
    id: "verina",
    name: "Verina",
    epithet: "Botanist of the New Federation",
    element: "spectro",
    role: "Universal healer & all-type DMG amplifier",
    weaponType: "Rectifier",
    set: "5pc Rejuvenating Glow · Bell-Borne Geochelone (Fallacy of No Return if you prefer faster Concerto over the shield) main",
    setAlt: "5pc Moonlit Clouds · 2pc Rejuvenating Glow + 2pc Moonlit Clouds",
    weapon: "Stellar Symphony",
    weaponAlt: "Variation · Call of the Abyss · Rectifier of Voyager · Rectifier#25",
    talents: "Forte Circuit = Liberation >> Skill > Intro > Normal Attack",
    stats: [
      { id: "main-4c", label: "4-Cost main stat", target: "Healing Bonus (never CRIT — nothing she does needs to crit)" },
      { id: "main-3c", label: "3-Cost main stats", target: "Energy Regen × 2 (ATK% only after ER goal is met)" },
      { id: "main-1c", label: "1-Cost main stats", target: "ATK% × 2" },
      { id: "er-target", label: "Energy Regen total", target: "150% floor; ~170–200% ideal (guides quote up to ~180–220% when she's the team's only energy battery)" },
      { id: "total-atk", label: "Total ATK", target: "~1,500–1,800 (all heals + Outro regen scale on ATK)" },
      { id: "substats", label: "Substat priority", target: "Energy Regen > ATK% > flat ATK > HP%" },
      { id: "crit-skip", label: "CRIT Rate / CRIT DMG", target: "Skip entirely — her personal damage is irrelevant" },
    ],
    note: "Her Liberation costs a hefty 175 Resonance Energy and her whole healing engine (Photosynthesis Mark) collapses if it isn't up every rotation — so the ER target and a Concerto/energy-generating weapon (Stellar Symphony or Variation) are non-negotiable before any other stat.",
    altBuilds: [
      {
        id: "moonlit-concerto-bot",
        label: "Moonlit Clouds ATK-bot",
        role: "Concerto-focused buffer when another unit already holds Rejuvenating Glow",
        set: "5pc Moonlit Clouds",
        weapon: "Variation",
        weaponAlt: "Rectifier of Voyager",
        talents: "Liberation = Forte Circuit > Skill > others",
        stats: [
          { id: "mc-main-4c", label: "4-Cost main stat", target: "ATK% (Healing Bonus if the team feels squishy)" },
          { id: "mc-main-3c", label: "3-Cost main stats", target: "Energy Regen × 2" },
          { id: "mc-main-1c", label: "1-Cost main stats", target: "ATK% × 2" },
          { id: "mc-er", label: "Energy Regen total", target: "170%+ — the 5pc outro effect (22.5% ATK to the next Resonator) demands an outro every rotation" },
        ],
        note: "Trades some raw healing for a stacked outro package (Moonlit 22.5% ATK + Blossom 15% Deepen) — mostly used in dual-support teams where Rejuvenating Glow is taken.",
      },
    ],
    deep: {
      lore: "A young botanist from the New Federation now dwelling in Jinzhou, Verina once roamed with a Pioneer Association expedition team and inevitably ended up as everyone's caretaker. Always smiling and endlessly tenacious for her age, she wishes for every flower — and every teammate — to be blessed with the miracle of life.",
      kit: [
        "Resonance Skill (Botany Experiment): quick Spectro poke that feeds her Forte gauge and Concerto — cast on cooldown, minimal field time required.",
        "Resonance Liberation (Arboreal Flourish, 175 energy): AoE Spectro DMG that applies Photosynthesis Mark — any teammate hitting marked enemies triggers coordinated healing, making her sustain fully off-field.",
        "Forte Circuit (Starflower Blooms): empowered Heavy Attack consuming Photosynthesis Energy for an on-demand team-wide burst heal plus follow-up Spectro hits.",
        "Outro (Blossom): 15% All-Type DMG Deepen for the WHOLE team for 30s — it persists through swaps and works for any element, consumed by whichever DPS is on field; this is where most of her value lives. Also drips healing (20% of her ATK every 5s) onto the incoming character.",
        "Inherent passive: once every 10 minutes, prevents fatal damage to nearby Resonators and heals them — a free team-wide cheat-death safety net.",
        "Intended as a ~10-second quick-swap presence: everything important she provides keeps running after she leaves the field.",
      ],
      tips: [
        "Standard rotation: Intro > Skill > Bell-Borne Echo > Liberation > Forte Heavy Attack (Starflower Blooms) > Outro into your DPS — pop the Echo right before swapping so the team keeps the 10% DMG boost + shield.",
        "Because Blossom's 15% Deepen is element-agnostic, slot her into literally any team that isn't already running Shorekeeper — she needs zero tuning per comp.",
        "If Concerto feels slow, run Fallacy of No Return as the main Echo or Variation as the weapon; skipping the last Starflower bloom once Concerto is full speeds rotations.",
        "Don't chase Healing Bonus substats over ER — heals are already overkill at S0; a missed Liberation costs far more than a smaller heal.",
      ],
      synergies: [
        { id: "encore", why: "The textbook pairing: her healing keeps Encore above the 70% HP damage threshold, and the full 30s of 15% All-Type DMG Deepen covers an entire Cosmos Rave window." },
        { id: "xuanling", why: "Field-greedy Havoc hypercarry — Verina does her whole buff/heal routine in ~10 seconds and lets Xuanling consume the long-duration Deepen uncontested." },
        { id: "danjin", why: "Danjin pays HP for every combo — Verina's off-field Photosynthesis healing and cheat-death passive are the classic enablers that let her drain freely." },
      ],
    },
  },
  {
    id: "yangyang",
    name: "Yangyang",
    epithet: "Outrider of the Midnight Rangers",
    element: "aero",
    role: "Support / Energy Battery",
    weaponType: "Sword",
    set: "5pc Moonlit Clouds · Impermanence Heron main",
    setAlt: "5pc Gusts of Welkin (Aero teams) · 5pc Sierra Gale (personal-damage stopgap)",
    weapon: "Emerald of Genesis",
    weaponAlt: "Sword#18 · Commando of Conviction · Sword of Voyager (craftable F2P) · Lunar Cutter",
    talents: "Forte Circuit > Liberation > Normal Attack > Skill > Intro",
    stats: [
      { id: "4cost-main", label: "4-Cost Main Stat", target: "CRIT Rate (or CRIT DMG — on a pure battery a spare crit piece is fine)" },
      { id: "3cost-main", label: "3-Cost Main Stats", target: "Energy Regen% + Aero DMG% (run double ER% until the ~150% goal is met)" },
      { id: "1cost-main", label: "1-Cost Main Stats", target: "ATK% ×2" },
      { id: "energy-regen", label: "Energy Regen", target: "140-150%+ — first priority; Game8 cites ~140% minimum for her rotation" },
      { id: "crit-rate", label: "CRIT Rate", target: "50-60% (only after the ER quota is filled)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "100-130% (~1:2 ratio; don't chase DPS-tier numbers on a 4-star support)" },
      { id: "total-atk", label: "Total ATK", target: "~1,500-1,800 — enough to make her Liberation hits meaningful" },
      { id: "substats", label: "Substat Priority", target: "Energy Regen > CRIT Rate/DMG > ATK% > Resonance Liberation DMG%" },
    ],
    note: "Her entire support payload triggers on actually casting the Outro: Whispering Breeze's 20 Resonance Energy, Moonlit Clouds' 22.5% ATK, and Impermanence Heron's 12% DMG amp all land on the Outro handoff — a raw swap gives your carry nothing. Hit ~140-150% Energy Regen before touching crit, and hand her Outro to a Liberation-reliant DPS, not whoever happens to be next.",
    deep: {
      lore: "A gentle former Outrider of Jinzhou's Midnight Rangers who hears voices on the wind, Yangyang raises her blade only to protect, tracing the same currents she listens to. A launch-roster 4-star, she has long since aged out of her early sub-DPS billing into the game's classic budget battery and grouping support. In 3.5 her story came full circle when her Havoc SP variant, Yangyang: Xuanling, debuted as Wuthering Waves' first SP Resonator — the base Aero Yangyang remains her own, separately-buildable unit.",
      kit: [
        "Resonance Skill — Zephyr Domain: a whirling wind vortex (usable mid-air) that vacuums nearby enemies to its center while dealing Aero DMG — her signature crowd-grouping tool.",
        "Resonance Liberation — Wind Spirals: a large multi-hit wind field that deals continuous Aero DMG in a generous radius, groups lighter enemies, and generates a big chunk of Concerto Energy, speeding her toward the Outro.",
        "Forte Circuit — Echoing Feathers: consumes Melodies to cast Heavy Attack: Stormy Strike (after a Heavy Attack or Dodge Counter) or Mid-air Attack: Feather Release (Basic Attack in mid-air); the Inherent Skill Compassion then refunds 30 Stamina after Feather Release, keeping her aerial loop fast.",
        "Outro — Whispering Breeze: funnels 4 Resonance Energy per second for 5s (20 total) to the incoming Resonator — the core of her modern role as an energy battery for Liberation-hungry carries.",
        "Where the value lives: the Outro energy plus the Moonlit Clouds 22.5% ATK and Impermanence Heron 12% DMG amp handoff, plus free grouping; her personal damage is a bonus. Per Prydwen she is fully quickswap-friendly — none of her buffs expire when she switches out.",
      ],
      tips: [
        "Standard exit: cast Impermanence Heron at the end of her field time, swap-cancel the animation, then Outro — the incoming carry inherits Heron's 12% DMG amp and Moonlit Clouds' 22.5% ATK together.",
        "Rush Energy Regen before anything else (double ER% 3-costs early is fine) — her value collapses if the Outro/Liberation cycle isn't ready every rotation.",
        "Time Wind Spirals just before your carry's AoE burst so enemies are still bunched when the big hits land.",
        "Keep her field time short: Intro > Skill > a Feather Release string > Liberation > Echo > Outro — she is a rotation lubricant, not an on-field DPS.",
      ],
      synergies: [
        { id: "xuanling", why: "Whispering Breeze's Outro energy feed patches her SP-variant's ER-hungry Liberation loop (115-120% target), and Yangyang's vortex grouping sets up the Melody-dump nuke — the two Yangyangs run surprisingly well together." },
        { id: "verina", why: "The classic F2P backline pair from launch that still works in 3.x — Verina's universal healing and damage amplification cover sustain while Yangyang covers energy and grouping, freeing both premium slots for carries." },
      ],
    },
  },
  {
    id: "sanhua",
    name: "Sanhua",
    epithet: "Captain of Jinhsi's Secret Guards",
    element: "glacio",
    role: "Quick-swap Glacio Sub-DPS / Basic Attack Amplifier",
    weaponType: "Sword",
    set: "5pc Moonlit Clouds · Impermanence Heron main",
    setAlt: "5pc Freezing Frost (personal-damage sub-DPS) · 2pc Moonlit Clouds + 2pc Freezing Frost (transitional)",
    weapon: "Emerald of Genesis",
    weaponAlt: "Overture (free 4★, solves her ER needs — best F2P pick) · Commando of Conviction · Lunar Cutter · Sword of Voyager (early-game ER stopgap)",
    talents: "Forte Circuit = Liberation > Skill >> Intro/Basic",
    stats: [
      { id: "main-4c", label: "4-cost main stat", target: "CRIT Rate (CRIT DMG if weapon/substats skew CR)" },
      { id: "main-3c", label: "3-cost main stats (x2)", target: "Glacio DMG %" },
      { id: "main-1c", label: "1-cost main stats (x2)", target: "ATK %" },
      { id: "crit-rate", label: "CRIT Rate", target: "60-70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "120-150%" },
      { id: "total-atk", label: "Total ATK", target: "1,700-2,000+" },
      { id: "energy-regen", label: "Energy Regen", target: "120-150% (low end is fine on 5pc Moonlit Clouds or with a battery like Yangyang; she must have Liberation every rotation)" },
      { id: "substat-prio", label: "Substat priority", target: "CRIT Rate / CRIT DMG > ATK% > Energy Regen" },
    ],
    note: "Her entire team value lives in her Outro, so she must reach 100 Concerto and swap out every rotation — Impermanence Heron's extra 12% DMG buff also only triggers on Outro. The 38% Deepen amplifies Basic Attack damage ONLY; on a Heavy-Attack or Liberation-centric carry (e.g. Xuanling, Hiyuki) she is just a quick-swap Glacio damage/Concerto bot, not an amplifier.",
    altBuilds: [
      {
        id: "freezing-frost-subdps",
        label: "Freezing Frost personal-damage sub-DPS",
        role: "Glacio burst sub-DPS (own damage over buffing)",
        set: "5pc Freezing Frost",
        weapon: "Emerald of Genesis",
        weaponAlt: "Overture · Commando of Conviction",
        talents: "Forte Circuit = Liberation > Skill > Basic",
        stats: [
          { id: "ff-main-4c", label: "4-cost main stat", target: "CRIT Rate or CRIT DMG" },
          { id: "ff-main-3c", label: "3-cost main stats (x2)", target: "Glacio DMG %" },
          { id: "ff-main-1c", label: "1-cost main stats (x2)", target: "ATK %" },
          { id: "ff-crit", label: "CRIT Rate / CRIT DMG", target: "65%+ / 140%+ (crit-first, ER deprioritized)" },
          { id: "ff-atk", label: "Total ATK", target: "2,000+" },
        ],
        note: "Only worth it if no teammate consumes her Basic Attack Deepen (e.g. Hiyuki teams) — Moonlit Clouds + Heron is otherwise strictly better for the team.",
      },
    ],
    deep: {
      lore: "Sanhua is the stoic captain of Magistrate Jinhsi's secret guards in Jinzhou, a swordswoman whose ice-aligned Forte once threatened to consume her. By severing herself from emotion she turned that curse into a blade of absolute frost, living only to protect the person who accepted her.",
      kit: [
        "Resonance Skill (Eternal Frost): instant ice burst that leaves an Ice Prism structure — cheap, fast damage and Concerto in a quick-swap window.",
        "Resonance Liberation (Glacial Gaze): AoE Glacio nuke that spawns a Glacier structure; needs ~120%+ ER (or Moonlit Clouds/battery support) to be up every rotation.",
        "Forte Circuit (Clarity of Mind): a rhythm-style timing gauge — release her charged Heavy Attack (Detonate) when the indicator hits the zone to shatter all Ice structures (Intro thorn, Skill prism, Liberation glacier) at once for her biggest personal hit.",
        "Intro Skill plants an Ice Thorn structure, letting her start her combo the moment she swaps in; she has one of the fastest Concerto rotations in the game (~5s of field time).",
        "Outro Skill (Silversnow): the incoming resonator's Basic Attack DMG is Amplified (Deepened) by 38% for 14s — this is where her value lives, consumed by an on-field Basic Attack carry.",
        "With 5pc Moonlit Clouds + Impermanence Heron she stacks +22% ATK and +12% DMG for the next character on top of the 38% Basic Deepen.",
      ],
      tips: [
        "Standard loop: Intro > Echo > Skill > Liberation > charged Heavy (Detonate) timed to shatter all three ice structures > Outro into your carry. Practice the Forte timing — mistimed Detonate loses a large chunk of her damage and Concerto.",
        "Don't over-invest in ER substats if she runs 5pc Moonlit Clouds and teammates feed her energy off-field; CRIT and ATK% rolls are worth more since she still contributes real burst damage.",
        "Only Outro into the character who actually uses Basic Attacks — the 38% Deepen and Heron's 12% are wasted if a healer swaps in after her.",
        "She is extremely cheap to gear: even a half-finished Sanhua delivers most of her value, making her the best budget/second-team amplifier for Basic Attack carries.",
      ],
      synergies: [
        { id: "rebecca", why: "Rebecca is a Basic Attack-scaling Electro pistols carry — she directly converts Sanhua's 38% Basic Attack Deepen and Heron/Moonlit buffs into damage while Sanhua needs almost no field time." },
        { id: "lingyang", why: "In Glacio teams Sanhua is the F2P quick-swap partner for Lingyang: ~5s rotations, Glacio resonance and fast Concerto keep his transformed windows fed (though his Liberation-form damage doesn't use the Basic Deepen)." },
        { id: "verina", why: "Verina remains the universal third slot: healing plus her own ATK/all-DMG amplification stacks with Sanhua's Outro, the classic budget triple-buff sandwich around any Basic Attack DPS." },
      ],
    },
  },
  {
    id: "encore",
    name: "Encore",
    epithet: "Woolies' Dearest Friend of the Black Shores",
    element: "fusion",
    role: "On-Field Fusion Main DPS (Basic Attack)",
    weaponType: "Rectifier",
    set: "5pc Molten Rift · Inferno Rider main",
    setAlt: "2pc Molten Rift + 2pc Lingering Tunes (transitional)",
    weapon: "Stringmaster",
    weaponAlt: "Cosmic Ripples (standard 5★) · Augment (4★ Battle Pass) · Rectifier of Voyager (early-game stopgap)",
    talents: "Basic Attack = Liberation > Forte Circuit > Skill > Intro",
    stats: [
      { id: "main-4c", label: "4-cost main stat", target: "CRIT Rate (CRIT DMG with Stringmaster's CR line)" },
      { id: "main-3c", label: "3-cost main stats (x2)", target: "Fusion DMG %" },
      { id: "main-1c", label: "1-cost main stats (x2)", target: "ATK %" },
      { id: "crit-rate", label: "CRIT Rate", target: "65-70%+" },
      { id: "crit-dmg", label: "CRIT DMG", target: "230-250% combined crit value (keep ~1:2 ratio)" },
      { id: "total-atk", label: "Total ATK", target: "2,000+" },
      { id: "energy-regen", label: "Energy Regen", target: "100-120% (Basic Woolies Attack and Skill each restore 10 Resonance Energy — she largely batteries herself)" },
      { id: "substat-prio", label: "Substat priority", target: "CRIT Rate / CRIT DMG > ATK% > Energy Regen" },
    ],
    note: "Nearly 70% of her damage is Basic Attacks inside Cosmos Rave — level Basic Attack alongside Liberation and do NOT build her around the Skill or Forte Circuit. Keep her HP above 70%: her Inherent Skill adds +10% DMG in Rave only while healthy, which quietly makes a healer part of her damage profile.",
    deep: {
      lore: "A Black Shores prodigy who looks like a child and negotiates like a senior operative, never seen without her sheep companions Cosmos and Abby. Her Fusion power runs on unfiltered emotion — when she loses patience mid-fight, the Woolies do too, and the resulting tantrum is measured in explosions.",
      kit: [
        "Resonance Liberation — Cosmos Rave: her core state. Basic Attacks transform into empowered Cosmos attacks and account for roughly 70% of her total output; the entire build serves this window.",
        "Lost Lamb stacks: during Cosmos Rave every hit grants +5% ATK for 10s, stacking to 6 — she ramps to +30% ATK inside her own burst window.",
        "Resonance Skill — Energetic Welcome: quick Fusion poke that restores 10 Resonance Energy; a rotation filler, not a damage centerpiece.",
        "Forte Circuit: spend the gauge on her enhanced Heavy Attack between Rave windows; secondary damage at best.",
        "Outro — Thermal Field: Fusion DMG Amplify for the incoming Resonator, letting her double as a buffer in double-Fusion teams.",
        "Inherent: +10% DMG during Cosmos Rave while above 70% HP — sustain indirectly buys damage.",
      ],
      tips: [
        "Rotation shape: build Concerto and energy with Skill + basics, take the buffer's Outro, cast Liberation, then stay on-field and burn the entire Cosmos Rave with basics — swapping early throws away her damage window.",
        "5pc Molten Rift wants the Skill cast BEFORE Liberation so the 15s Fusion DMG buff covers the whole Rave window.",
        "Stringmaster is her real BiS despite being Yinlin's signature — the CR line fixes her crit budget and the DMG% clause ramps during setup. Cosmic Ripples is the best standard-banner option.",
      ],
      synergies: [
        { id: "sanhua", why: "Her canonical partner: the 38% Basic Attack Deepen Outro lands on exactly the ~70% of Encore's damage that is Basic Attacks, and Sanhua's ~5s field time barely interrupts the Rave loop." },
        { id: "verina", why: "The classic third slot: healing keeps Encore above the 70% HP threshold for her +10% Rave bonus, and Verina's +20% team ATK plus universal Amplify stack on top." },
        { id: "shorekeeper", why: "Premium alternative to Verina — bigger universal amplification and crit support from the Stellarealm, with the same keep-her-healthy insurance for the Inherent Skill bonus." },
      ],
    },
  },
];

export const ATTRIBUTE_ORDER = ["glacio", "fusion", "electro", "aero", "spectro", "havoc"];
