/* ============================================================
   WUTHERING WAVES — RESONATOR DATA
   Converted to the shared CharacterCard field shape.
   `element` holds the attribute key used for theme lookup.
   ============================================================ */

export const WUWA_VERSION = "3.5";

export const ATTRIBUTE_THEME = {
  glacio:  { color: "#9fd8e8", glow: "rgba(159,216,232,0.18)", label: "Glacio" },
  fusion:  { color: "#e8875d", glow: "rgba(232,135,93,0.18)",  label: "Fusion" },
  electro: { color: "#c58ae0", glow: "rgba(197,138,224,0.18)", label: "Electro" },
  aero:    { color: "#7fd4b5", glow: "rgba(127,212,181,0.18)", label: "Aero" },
  spectro: { color: "#e8d27f", glow: "rgba(232,210,127,0.18)", label: "Spectro" },
  havoc:   { color: "#d17a9e", glow: "rgba(209,122,158,0.18)", label: "Havoc" },
};

export const RESONATORS = [
  {
    id: "xuanling",
    name: "Yangyang: Xuanling",
    epithet: "Votary of the Voice",
    element: "havoc",
    role: "Main DPS",
    weaponType: "Sword",
    set: "5pc Song of Feathered Trace · Thousand-Puppet Pavilion main",
    setAlt: "5pc Havoc Eclipse · 5pc Thread of Severed Fate",
    weapon: "Azure Oath",
    weaponAlt: "Emerald Sentence · Red Spring · Emerald of Genesis · Lumingloss",
    talents: "Forte Circuit >> Liberation > Normal > Skill = Intro",
    stats: [
      { id: "4cost-main", label: "4-Cost Main Stat", target: "CRIT DMG (her set + signature already stack CRIT Rate)" },
      { id: "3cost-main", label: "3-Cost Main Stats", target: "Havoc DMG% x2" },
      { id: "1cost-main", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "~50% sheet → 65-70% in combat (set Feather grants +20%)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "220-250% (keep ~1:2 ratio vs CRIT Rate)" },
      { id: "total-atk", label: "Total ATK", target: "1900-2200 fully buffed" },
      { id: "energy-regen", label: "Energy Regen", target: "115-120% so Liberation is up every rotation" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate/DMG > Heavy Attack DMG > ATK% > ER" },
    ],
    note: "Do not default to CRIT Rate on the 4-cost: Song of Feathered Trace's Feather buff (+20% CRIT Rate on inflicting Havoc Bane) plus Azure Oath already push her rate high, so CRIT DMG avoids overcapping. And because Liberation is ~37% of her damage, dropping below ~115% Energy Regen quietly wrecks her rotation.",
    deep: {
      lore: "Second daughter of the famed Xuanling musical dynasty of Mingting and younger sister of Suisui, Yangyang bears the rare gift of communing with the Streams — the \"Votary of the Voice.\" Once an Outrider of Jinzhou's Midnight Rangers, she now stands as acting Xuan Watcher at Xuanfang Hold, her blade raised only to protect. She is Wuthering Waves' first SP Resonator, a Havoc-attuned reimagining of the original Aero outrider.",
      kit: [
        "Resonance Skill — Sword Stance Flow: cycles between Azure and Feather Sword Stances; empowered stance-switch casts deal Havoc DMG counted as Heavy Attack DMG and refill her Melody gauge (max 100).",
        "Both stances' Basic Attack chains apply Havoc Bane on their finishers; Havoc Bane in turn feeds her self-buffs — Streaming Storm (+160% CRIT DMG) and Feathered Oath (up to +150%) reward staying in Feather Sword Stance.",
        "Resonance Liberation — Hush of a Thousand Voices: spends all Melody on a massive Havoc Heavy Attack hit, instantly maxes Havoc Bane stacks on everything hit, and grants Voice upon Voice so the next Sword Stance Flow summons Shadow of Xuanling for a bonus Heavy Attack hit.",
        "Outro — As the Wind Wills: grants Tonal Switch to teammates for 20s, amplifying their Havoc DMG by 20% the next time they inflict Havoc Bane.",
        "Damage split: Forte Circuit ~58%, Liberation ~37%, Basic ~4%, Intro ~1% — nearly everything she does snapshots as Heavy Attack DMG, so Heavy Attack buffers multiply her whole kit.",
      ],
      tips: [
        "Core rotation: Intro (Skybound Feather) → Liberation → Sword Stance Flow: Feather → Feather-stance Heavy → Havoc in Bloom I-III basic chain → Echo (Thousand-Puppet Pavilion) → Outro; keep Havoc Bane active the entire time.",
        "Run the 4-3-3-1-1 layout: CRIT DMG 4-cost, double Havoc DMG% 3-costs, ATK% 1-costs; roll substats toward CRIT first, then Heavy Attack DMG.",
        "Thousand-Puppet Pavilion's Blades of Thousand Memories detonate when Havoc Bane is inflicted — cast the Echo before her Bane-applying finishers, not after.",
        "On Emerald of Genesis (best F2P pick), her frequent stance-switch Skill casts keep the ATK stacks up and the extra Energy Regen loosens her ER substat requirement.",
      ],
      synergies: [
        { id: "suisui", why: "Her older sister and 3.5 partner banner Glacio support; the Xuanling-Suisui core leans into the same Negative Status loop — Xuanling keeps Havoc Bane rolling and Suisui converts it into a bigger payoff via Ceaseless Landscape." },
        { id: "phrolova", why: "Buffs exactly what Xuanling scales from — Havoc DMG and Heavy Attack DMG — while adding off-field Havoc damage during Xuanling's field time." },
        { id: "shorekeeper", why: "Universal sustain slot: continuous healing plus CRIT buffs from her Liberation field, adding a damage-amp layer without competing for field time." },
      ],
    },
  },
  {
    id: "suisui",
    name: "Suisui",
    epithet: "Dawn of Truth",
    element: "glacio",
    role: "Support / Healer",
    weaponType: "Rectifier",
    set: "5pc Song of Feathered Trace · Fallacy of No Return main",
    setAlt: "5pc Rejuvenating Glow · 5pc Moonlit Clouds",
    weapon: "Firstlight's Herald",
    weaponAlt: "Stellar Symphony · Variation · Call of the Abyss · Rectifier#25",
    talents: "Liberation > Forte > Skill > Intro/Outro >> Normal",
    stats: [
      { id: "main-4c", label: "4-Cost Main Stat", target: "HP% (or Healing Bonus% if the team takes heavy hits) — not Crit" },
      { id: "main-3c", label: "3-Cost Main Stats", target: "Energy Regen% ×2 (swap to HP% only after ER goal is met)" },
      { id: "main-1c", label: "1-Cost Main Stats", target: "HP% ×2" },
      { id: "er-target", label: "Energy Regen", target: "~260% (buffs scale on ER above 200%; sig weapon covers a large chunk)" },
      { id: "total-hp", label: "Total HP", target: "~30,000+ for comfortable sustain (heals scale on Max HP)" },
      { id: "crit-rate", label: "CRIT Rate", target: "Skip — she is a pure support, crit adds nothing to her buffs" },
      { id: "crit-dmg", label: "CRIT DMG", target: "Skip — spend those rolls on ER / HP%" },
      { id: "substats", label: "Substat Priority", target: "Energy Regen > HP% > Flat HP > Healing Bonus" },
    ],
    note: "Energy Regen IS her damage stat: Chongming's Feather (5pc set) and her Rippling Waters tiers convert ER above 200% into teamwide ATK/DMG, with ~260% ER as the community breakpoint — building her like a crit rectifier or a pure HP tank throws away most of her team value. Also, her Outro is only as strong as the Floral Epistle she banks before swapping out.",
    deep: {
      lore: "Born into a noble family of Mingting, Suisui is the brilliant young director of the Zhaoming Chamber of Commerce in Mengzhou — and Yangyang's older sister, sharing the Chongming Bird as her Resonance source and a Tacet Mark on her forehead. Lively, sharp-tongued and effortlessly sociable, she weaves market intelligence from across Huanglong into her deals, fighting with a water fan as her Rectifier.",
      kit: [
        "Dual-stance Forte: in Zephyr Stance her Basic Attacks, dodges and Dodge Counters build Cloud Breath; when full she casts Awakening Spring, pulling enemies in, applying Glacio Chafe and granting the team Enrichment (healing).",
        "In Drizzle Stance she banks Floral Epistle from Basics/Heavies/dodges — the amount stored before she swaps out directly sets the power of her Outro.",
        "Resonance Liberation — Ceaseless Landscape: raises the team's Negative Status (attribute anomaly) stack limits and anchors her healing loop, making her the sustain of choice for anomaly comps.",
        "Outro — Rippling Waters: always grants the whole team 25% All-Type DMG Amplification for 30s; at 200/400/600 Floral Epistle it adds Plume Step, an ER-scaling DMG buff (over 200% ER) and Undulating Mist ATK stacks for the incoming Resonator.",
        "Her 'damage' lives almost entirely in her buffs: with 5pc Song of Feathered Trace, inflicting Glacio Chafe grants the team up to +25% ATK scaling off her Energy Regen.",
      ],
      tips: [
        "Rush ~260% Energy Regen before anything else — ER mains on both 3-costs plus her signature (or an ER 4-star like Variation/Rectifier#25) gets you there; her buffs fall off sharply below 200%.",
        "Bank 600 Floral Epistle in Drizzle Stance before swapping out to unlock all three Rippling Waters tiers, then cast Liberation so the amp window and raised anomaly caps overlap your DPS's burst.",
        "Pick Healing Bonus over HP% on the 4-cost only if your team is actually dying; otherwise HP% (or a set-piece 4-cost like Fallacy of No Return / Forbidden Bastion) is the standard call.",
        "She slots into almost any team, but she is at her best in Negative Status comps — keep her Glacio Chafe application constant to maintain Chongming's Feather uptime.",
      ],
      synergies: [
        { id: "hiyuki", why: "Hiyuki's Glacio Chafe hypercarry team is Suisui's flagship home — all pieces feed the same Negative Status engine while Suisui adds healing, 25% All-DMG amp and ER-scaled ATK." },
        { id: "xuanling", why: "Xuanling hits extremely hard but is fragile; Suisui's Ceaseless Landscape amplifies her Havoc anomaly output while Enrichment healing stops the one-shots — widely called her second-best pairing." },
        { id: "cartethyia", why: "Cartethyia wants enemies loaded with Aero Erosion stacks; Suisui raises the stack ceiling and hands her a long All-DMG amplification window (often run alongside Ciaccona)." },
      ],
    },
  },
  {
    id: "luuk-herssen",
    name: "Luuk Herssen",
    epithet: "Phase Transition",
    element: "spectro",
    role: "Main DPS",
    weaponType: "Gauntlets",
    set: "5pc Rite of Gilded Revelation · Twin Nova: Nebulous Cannon main",
    setAlt: "5pc Celestial Light",
    weapon: "Daybreaker's Spine",
    weaponAlt: "Pulsation Bracer · Abyss Surges · Blazing Justice · Celestial Spiral (4★)",
    talents: "Skill >> Liberation > Forte Circuit > Basic Attack > Intro",
    stats: [
      { id: "cost4-main", label: "4-Cost Main Stat", target: "CRIT Rate (or CRIT DMG — keep the 1:2 ratio)" },
      { id: "cost3-main", label: "3-Cost Main Stats", target: "Spectro DMG% x2" },
      { id: "cost1-main", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "65–70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "230–250% (~240% ideal)" },
      { id: "total-atk", label: "Total ATK", target: "~2,000+" },
      { id: "energy-regen", label: "Energy Regen", target: "≥120%" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate = CRIT DMG > ATK% > Basic Attack DMG% > Flat ATK" },
    ],
    note: "His Enhanced Skill loop (Aureole of Execution) is tagged as Basic Attack DMG, so the Rite of Gilded Revelation's 40% Basic ATK line and Basic Attack DMG% substats all apply — Celestial Light is only a stopgap that gives up that entire bonus. And don't skimp on Energy Regen: below ~120% his 3-stack Liberation finisher slips out of the rotation and the whole loop deflates.",
    deep: {
      lore: "Head physician of the Resonator Nursing Unit at Startorch Academy — attending doctor and mental-health counselor by day, a man with a conspicuously mysterious past by every other measure. Released in Version 3.1 as the premier Tune Strain DPS, he fights the way he practices medicine: precise, airborne, and always three moves ahead of the diagnosis.",
      kit: [
        "Resonance Skill: cycles through three Enhanced Resonance Skill forms; landing the 4th Basic Attack stage or 3rd Aerial Attack stage replaces his Skill with the Aureole of Execution — the core of his relentless mid-air loop.",
        "Forte Circuit: each Aureole of Execution stacks 'Endnotes on the Endgame' (max 3); every stack raises the DMG multiplier of his Liberation by 25%.",
        "Resonance Liberation (Rewritten in Winter's Margins): the big Spectro finisher — cast it at 3 Endnote stacks each rotation, which is why the ≥120% ER floor matters.",
        "Tune Strain engine: inflicts Tune Strain – Shifting/Interfered on hit, gaining Basic Attack DMG Amplification and DEF-ignore; teammates' Tune Break boosts amplify him further.",
        "Where the damage lives: the Basic-Attack-tagged Aureole of Execution loop makes up the bulk, capped off by the stacked Liberation nuke; his Intro/Outro contribution is minimal — he's a selfish on-fielder.",
      ],
      tips: [
        "Rotation in one sentence: finish the basic/aerial chain to unlock Aureole of Execution, cast three Enhanced Skills to stack Endnotes x3, then drop Liberation.",
        "Swap him in right after Mornye's Outro — her 25% teamwide DMG Amplification lasts 30s, covering his entire field phase.",
        "Stay airborne: his enhanced kit is built around aerial pressure; grounded play wastes his Aerial Attack stage triggers.",
        "F2P weapon path: Pulsation Bracer (3.0 standard 5★) is a near-mechanical copy of his signature and is recommended for most players; 4★ Celestial Spiral only as a stopgap.",
      ],
      synergies: [
        { id: "mornye", why: "Best-in-slot support: her Outro is a teamwide 25% All-DMG Amplification for 30s, and she responds to Tune Strain – Interfered, feeding Luuk's Tune Break damage bonuses." },
        { id: "lynae", why: "Premier Tune Strain sub-DPS: adds Tune Strain stack generation and extra Tune Strain buffs off-field, raising the team's max stack potential and Tune Break efficiency." },
        { id: "shorekeeper", why: "Plug-and-play sustain with a teamwide 15% DMG Amplified Outro — the safe third slot when Mornye/Lynae comps aren't available." },
      ],
    },
  },
  {
    id: "hiyuki",
    name: "Hiyuki",
    epithet: "Futures' Tithe",
    element: "glacio",
    role: "Main DPS",
    weaponType: "Sword",
    set: "5pc Wishes of Quiet Snowfall · Reminiscence: Threnodian – Voidborne Construct main",
    setAlt: "5pc Freezing Frost",
    weapon: "Frostburn",
    weaponAlt: "Emerald of Genesis · Blazing Brilliance · Feather Edge (R5) · Commando of Conviction",
    talents: "Liberation >> Forte = Normal > Skill",
    stats: [
      { id: "cost4-main", label: "4-Cost Main Stat", target: "CRIT DMG (set's +25% CR proc makes CRIT Rate overcap)" },
      { id: "cost3-main", label: "3-Cost Main Stats", target: "Glacio DMG% ×2 (ATK% acceptable on one)" },
      { id: "cost1-main", label: "1-Cost Main Stats", target: "ATK% ×2" },
      { id: "crit-rate", label: "CRIT Rate", target: "~70% sheet (Snowfall's +25% CR proc pushes combat CR toward 95-100%)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "230–260% (community 70:250 ratio)" },
      { id: "total-atk", label: "Total ATK", target: "1,900–2,200 buffed" },
      { id: "energy-regen", label: "Energy Regen", target: "~120% (110–125%)" },
      { id: "substat-prio", label: "Substat Priority", target: "CRIT > ER to 120% > Lib DMG% > ATK%" },
    ],
    note: "Take CRIT DMG, not CRIT Rate, on the 4-cost: Wishes of Quiet Snowfall's Snowfall effect grants +25% Crit Rate whenever she deals Resonance Liberation DMG, so a Crit Rate main stat overcaps in her Foreclaimed Self form where nearly all her damage lives. Also don't skip ER (~120%) — her entire loop stalls if the transformation isn't up.",
    deep: {
      lore: "The Miko of the Flaming Sakura of Ashinohara, Hiyuki is the last and sole member of the Special Response Force stationed in Lahai-Roi, standing guardian over the Dimmr Plains and the Spacetrek Collective's researchers. For over a century the mikos tithed their lifespans to hold back the Threnodian Aleph-1, which grows stronger with every cycle — Hiyuki chose to be the last to carry that burden.",
      kit: [
        "Present Self form: 3rd-stage Basic Attacks build Dedication; Resonance Skill \"Present Self\" also buffs all nearby Resonators' DMG +20% for 30s.",
        "At full Forte gauge, an empowered Heavy Attack unlocks her first Resonance Liberation, transforming her into the Foreclaimed Self.",
        "Foreclaimed Self is where the damage lives: every attack is empowered, applies Glacio Chafe, and scales off Resonance Liberation DMG.",
        "Building Frostheart lets her enter Iai Stance — each Iai cast grants a Snowforged Blade stack (max 3), consumed by her nuke Foreclaiming: Blade Liberation for a higher multiplier per stack.",
        "Intro Skill grants 2 Dedication stacks and auto-performs the 3rd Basic Attack stage (a 3rd stack), fast-tracking her transformation; she is a long-field-time hypercarry.",
      ],
      tips: [
        "Always enter via Intro Skill: it banks ~3 Dedication stacks instantly, letting you reach Foreclaimed Self almost immediately instead of ramping with Basic Attacks.",
        "Bank all 3 Snowforged Blade stacks via repeated Iai casts before dropping Foreclaiming: Blade Liberation — the nuke's multiplier scales with stacks spent.",
        "Frostburn is BiS by a clear margin (Glacio Chafe amp + DEF ignore); Emerald of Genesis runs ~91% of it and its ER solves her 120% Energy Regen requirement cheaply.",
        "Cast Present Self early each rotation to keep the 20% team DMG buff rolling, then commit to her long on-field burst window.",
      ],
      synergies: [
        { id: "lynae", why: "Top sub-DPS pairing: her handoff carries Resonance Liberation DMG Amplification plus All-DMG support, exactly matching Hiyuki's Lib-scaling Foreclaimed Self burst profile." },
        { id: "shorekeeper", why: "Hypercarry glue — healing, Concerto batteries, and a fully upgraded Stellarealm with Crit buffs active by the time Hiyuki intros into her long DPS window." },
      ],
    },
  },
  {
    id: "cartethyia",
    name: "Cartethyia",
    epithet: "The Sea God's Chosen",
    element: "aero",
    role: "Main DPS",
    weaponType: "Sword",
    set: "5pc Windward Pilgrimage · Reminiscence: Fleurdelys main",
    setAlt: "5pc Gusts of Welkin · 5pc Sierra Gale (stopgap)",
    weapon: "Defier's Thorn",
    weaponAlt: "Red Spring · Emerald of Genesis · Guardian Sword (3★ F2P, HP%)",
    talents: "Forte Circuit >> Normal Attack > Liberation > Skill > Intro",
    stats: [
      { id: "4c-main-a", label: "4-cost main (slot 1)", target: "CRIT Rate" },
      { id: "4c-main-b", label: "4-cost main (slot 2)", target: "CRIT DMG (run double 4-cost, 44111)" },
      { id: "1c-mains", label: "1-cost mains x3", target: "HP% (never ATK%)" },
      { id: "3c-fallback", label: "3-cost mains (only if stuck on 43311)", target: "Aero DMG% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "65-70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "250-280% (aim ~70:270 ratio)" },
      { id: "total-hp", label: "Total HP", target: "48,000-52,000 (~50k sweet spot)" },
      { id: "energy-regen", label: "Energy Regen", target: "115-120% with Ciaccona; ~125% otherwise" },
    ],
    note: "Cartethyia scales entirely off HP — ATK anywhere on her gear is a dead stat. She is one of the only carries who prefers the 44111 echo layout (double 4-cost CRIT Rate + CRIT DMG, triple 1-cost HP%) over the standard 43311, because her kit, set, and signature already saturate her Aero DMG% bonus.",
    deep: {
      lore: "A timid young saintess of Rinascita who prevailed in the Grand Gala's trial and inherited the will of the Sentinel Fleurdelys, Cartethyia now carries two souls in one body: the soft-spoken girl with her shortsword, and the imperious Sea God's blade that answers when she calls. Her doubt and the Sentinel's certainty take turns holding the same sword.",
      kit: [
        "Resonance Skill and combos apply Aero Erosion and summon Sword Shadows — Sword of Divinity (4th Normal, +50% Aero Erosion DMG and faster ticks), Sword of Discord (Heavy/Intro, equalizes Erosion stacks to the highest present), Sword of Virtue (Skill).",
        "Plunging Attacks recall active Sword Shadows for bonus damage; recalled types also empower her transformation.",
        "Resonance Liberation cuts her to 50% Max HP and transforms her into Fleurdelys for a 12s Manifest state with an entirely new, harder-hitting moveset.",
        "Forte Circuit: Fleurdelys-form attacks build Conviction; at 120 she unleashes Resonance Liberation: Blade of Howling Squall — the single biggest hit in her kit.",
        "Outro grants a long (20s) Aero DMG Amplify to the incoming ally, but only against targets carrying negative statuses.",
        "Real damage distribution: Fleurdelys-form combos + the Howling Squall finisher, multiplied by amplified Aero Erosion ticks — keep Erosion stacked at all times.",
      ],
      tips: [
        "Set up before you transform: land 4th Normal, Heavy, and Skill to place all three Sword Shadows, plunge to recall them, then Liberate — recalled swords buff the Fleurdelys state.",
        "Keep Aero Erosion permanently applied (Ciaccona is ideal) — it powers both her 50%-boosted Erosion ticks and the Windward Pilgrimage 30% Aero DMG / 10% CRIT Rate proc.",
        "The drop to 50% HP on Liberation is a feature, not a fail state — don't burn healer rotations panicking; Shorekeeper's passive healing covers it.",
        "Hit 115-120% Energy Regen from substats/weapon so Fleurdelys is up every rotation; past that, every roll goes to CRIT and HP%.",
      ],
      synergies: [
        { id: "ciaccona", why: "Best partner in the game for her: applies and amplifies Aero Erosion off-field (+100% Erosion DMG on Outro), keeping Windward Pilgrimage and Cartethyia's Erosion multipliers running with a very short rotation." },
        { id: "shorekeeper", why: "Free team-wide CRIT Rate/CRIT DMG and constant passive healing that safely offsets the 50% HP cost of Cartethyia's transformation." },
      ],
    },
  },
  {
    id: "phrolova",
    name: "Phrolova",
    epithet: "Fractsidus Overseer — Conductor of Souls",
    element: "havoc",
    role: "Off-Field DPS",
    weaponType: "Rectifier",
    set: "3pc Dream of the Lost + 2pc Havoc Eclipse · Nightmare: Hecate main",
    setAlt: "3pc Dream of the Lost + 2pc Midnight Veil · 5pc Havoc Eclipse",
    weapon: "Lethean Elegy",
    weaponAlt: "Stringmaster · Whispers of Sirens · Cosmic Ripples (standard 5★) · Augment",
    talents: "Liberation >> Normal Attack > Forte Circuit > Intro > Skill",
    stats: [
      { id: "4c-main", label: "4-Cost Main Stat", target: "CRIT DMG (CRIT Rate only if you sit well under ~70%)" },
      { id: "3c-main", label: "3-Cost Main Stats", target: "Havoc DMG% ×2" },
      { id: "1c-main", label: "1-Cost Main Stats", target: "ATK% ×2" },
      { id: "crit-rate", label: "CRIT Rate", target: "70–85% (easy to overcap — never exceed 100%)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "230–280%" },
      { id: "total-atk", label: "Total ATK", target: "~1,900–2,200" },
      { id: "energy-regen", label: "Energy Regen", target: "100% (base) — she needs ZERO extra ER" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate ≥ CRIT DMG > ATK% ≥ Resonance Skill DMG%" },
    ],
    note: "Phrolova is the game's first Resonator that uses no Resonance Energy at all — her Liberation is charged purely by Forte Volatile Notes — so any Energy Regen roll is a dead stat, and keeping 0 energy is what activates Dream of the Lost's +20% CRIT Rate / +35% Echo Skill DMG. With that set plus Lethean Elegy's 24.3% CRIT Rate, most players overcap CRIT Rate: run a CRIT DMG 4-cost, not CRIT Rate.",
    deep: {
      lore: "A Fractsidus Overseer who walks the line between life and death, Phrolova is an uncanny conductor whose baton attunes the frequencies of being and conducts symphonies of souls. Once a musician, a life of grief and betrayal — a past of which she was the sole survivor — drove her to the Fractsidus, where she labors to rekindle what was lost, even if she must summon a legion of Echoes to do it.",
      kit: [
        "Basic Attack 3, Resonance Skill, and their enhanced follow-ups generate Volatile Notes (max 6): red notes hit harder, blue notes group enemies, purple do both. At 6 notes her Heavy Attack becomes Scarlet Coda, a huge Havoc nuke and key secondary damage source.",
        "Scarlet Coda unlocks her Resonance Liberation, which summons Hecate and puts Phrolova in the 24s Maestro state — Hecate keeps attacking even after Phrolova swaps out, and Hecate is where the majority of her damage lives.",
        "Forte gimmick: she runs on 0 Resonance Energy — Liberation is fueled entirely by the Forte note gauge, letting her exploit Dream of the Lost's unconditional bonuses and skip ER entirely.",
        "Echo Skill casts by anyone on the team trigger Hecate's Enhanced Attacks off-field; her kit amplifies Echo Skill DMG by 80% and casting an Echo Skill grants the team 20% Attribute DMG for 30s — hence her love of Echo-spam teams.",
        "Outro Skill grants the incoming Resonator 20% Havoc DMG Amplification and 25% Heavy Attack DMG Amplification for 14s, making her a premier Havoc/Heavy-attack enabler as well as an off-field carry.",
      ],
      tips: [
        "Rotation core: build 6 Volatile Notes, fire Scarlet Coda, cast Liberation to deploy Hecate, then swap out — Hecate only deals off-field damage during the 24s Maestro window, so re-summon on cooldown.",
        "Build the team around frequent Echo Skill casts (Echo-skill spam comps) so Hecate constantly triggers Enhanced Attacks while Phrolova is benched.",
        "Aim for purple notes where possible and use blue notes for grouping in AoE content; red notes for single-target.",
        "Ignore Energy Regen completely and check your CRIT Rate before slotting a CRIT Rate 4-cost — with signature weapon + Dream of the Lost you likely already sit near cap.",
      ],
      synergies: [
        { id: "xuanling", why: "Phrolova's Outro (20% Havoc Amp + 25% Heavy Attack Amp) is tailor-made for Xuanling's Havoc Bane heavy-attack carry gameplay, and Hecate adds off-field pressure while Xuanling fields — a flagship 3.5 team." },
        { id: "mornye", why: "Mornye's 25% All-Type DMG Amplification Outro, heals, and buff fields turn off-field Phrolova into a true backline carry while covering the sustain slot." },
        { id: "shorekeeper", why: "Universal healer-buffer whose CRIT field and All-Type Amp fit any Phrolova comp when a dedicated Echo-skill partner or Mornye isn't available." },
      ],
    },
  },
  {
    id: "augusta",
    name: "Augusta",
    epithet: "Ephor of Septimont",
    element: "electro",
    role: "Main DPS",
    weaponType: "Broadblade",
    set: "3pc Crown of Valor + 2pc Void Thunder · The False Sovereign main",
    setAlt: "5pc Void Thunder · 3pc Crown of Valor + 2pc Lingering Tunes",
    weapon: "Thunderflare Dominion",
    weaponAlt: "Verdant Summit · Ages of Harvest · Aureate Zenith · Helios Cleaver (F2P)",
    talents: "Forte >> Liberation > Skill > Normal > Intro",
    stats: [
      { id: "main-4c", label: "4-cost main stat", target: "CRIT Rate (CRIT DMG if weapon gives CRIT Rate is balanced — keep ~1:2 ratio)" },
      { id: "main-3c", label: "3-cost main stats", target: "Electro DMG% ×2 (ATK% only as a stopgap)" },
      { id: "main-1c", label: "1-cost main stats", target: "ATK% ×2" },
      { id: "crit-rate", label: "CRIT Rate", target: "70–80%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "220–250%" },
      { id: "total-atk", label: "Total ATK", target: "2,100+" },
      { id: "energy-regen", label: "Energy Regen", target: "110–120% (first priority until met)" },
      { id: "substats", label: "Substat order", target: "ER (until met) > CRIT Rate = CRIT DMG > Heavy Attack DMG% = ATK% > flat ATK" },
    ],
    note: "Crown of Valor is a 3-piece sonata, not a 5-piece — its ATK/CRIT DMG stacks only trigger on gaining a shield, which Augusta's own kit provides, so pair it with 2pc Void Thunder and don't run it on characters who can't self-shield. Also don't zero out Energy Regen: her whole rotation hinges on getting both Ultimate phases off, so hit 110–120% ER before chasing more crit.",
    deep: {
      lore: "Once an undefeated gladiator of Septimont's arena, Augusta crushed every challenger to become champion and fought her way from the sands into the Ephor's seat. A mere mortal among Resonators, she mastered combat, statecraft, and her Forte through sheer iron will, and rules as a fiercely resilient yet humble leader crowned in the image of the sun.",
      kit: [
        "Forte Circuit runs three gauges: Prowess (purple bar) fills from Basics/Heavies/Skill/Intro and unlocks her Enhanced Heavy Attack; Ascendancy (solar crown) fills from nearly everything and unlocks the Enhanced Resonance Skill; Majesty (2 points) gates her second Ultimate.",
        "Enhanced Resonance Skill at full Ascendancy: she mounts a griffon and dives, triggering a ~7-second full time stop — enemies, timers, and buff durations all freeze while she attacks in quick succession.",
        "Resonance Liberation is two-phase: a huge slash, then with 2 Majesty points a hidden-blade follow-up Ultimate that ends her rotation — roughly 60% of her total damage carries the Liberation tag.",
        "Chained Resonance Skill casts and her base Skill/Intro refill Prowess and Ascendancy; the base Ultimate tops off the last ~10% Ascendancy she'd otherwise miss.",
        "Outro grants the next Resonator 15% All-Attribute DMG Amplification and refunds Augusta 1 Majesty point, keeping her flexible in any team.",
        "Damage lives in Heavy Attack- and Liberation-tagged burst windows, which is why Heavy Attack DMG% and the False Sovereign's 12% Electro + 12% Heavy DMG passive are core.",
      ],
      tips: [
        "Standard loop: Intro > Resonance Skill > Enhanced Heavy > base Ultimate > Enhanced Resonance Skill (time stop) > second Ultimate at 2 Majesty > Outro into your buffer.",
        "Apply teammate buffs BEFORE the griffon dive — buff durations freeze during the 7s time stop, so pre-stacked amps cover her entire burst.",
        "On echoes, chase double-crit rolls first, then Heavy Attack DMG%; get ER to 110–120% before anything else or her second Ultimate won't be up per rotation.",
        "If you lack Thunderflare Dominion, Verdant Summit's 48% Heavy Attack DMG makes it nearly comparable and is the best borrowed option.",
      ],
      synergies: [
        { id: "shorekeeper", why: "Best-in-slot universal support: healing, ER, and team-wide CRIT buffs cover Augusta's stat checks while she hogs field time." },
        { id: "lynae", why: "Top generalist buffer of the 3.x era; her amps line up with Augusta's frozen-buff time-stop burst window." },
        { id: "mornye", why: "Pairs with Lynae as an unmatched generalist buffing duo per Prydwen, feeding Augusta's Liberation-heavy damage profile." },
      ],
    },
  },
  {
    id: "galbrena",
    name: "Galbrena",
    epithet: "Fiend of Ever-Burning Flame",
    element: "fusion",
    role: "Main DPS",
    weaponType: "Pistols",
    set: "3pc Flamewing's Shadow + 2pc Molten Rift · Corrosaurus (3-cost) main",
    setAlt: "5pc Molten Rift · 3pc Flamewing's Shadow + 2pc Flaming Clawprint",
    weapon: "Lux & Umbra",
    weaponAlt: "Phasic Homogenizer · The Last Dance · Static Mist · Relativistic Jet (4★ F2P)",
    talents: "Forte Circuit >> Liberation > Basic Attack > Skill > Intro",
    stats: [
      { id: "main-4cost", label: "4-Cost Main Stat", target: "CRIT Rate (or CRIT DMG to balance ratio)" },
      { id: "main-3cost", label: "3-Cost Main Stats", target: "Fusion DMG% x2 (ATK%+Fusion only ~2% worse)" },
      { id: "main-1cost", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "~75% (counting Flamewing's Shadow procs)" },
      { id: "crit-dmg", label: "CRIT DMG", target: "~250%" },
      { id: "total-atk", label: "Total ATK", target: "2,000-2,200 (buffed)" },
      { id: "energy-regen", label: "Energy Regen", target: "110% minimum / 120% comfortable" },
      { id: "substats", label: "Substat Priority", target: "CRIT > ER > ATK% > Heavy Attack DMG" },
    ],
    note: "Her \"main\" echo is the 3-cost Corrosaurus, not a 4-cost — you run a 4-3-3-1-1 layout with CRIT on the off-slot 4-cost. And you must actually cast her Echo Skill every rotation: it fills her Afterflame gauge and triggers Flamewing's Shadow's crit buffs, so treating the echo as a stat stick guts her damage.",
    deep: {
      lore: "Once a Septimontian girl named Angel, Augusta's childhood friend, she was swallowed by the Dark Tide when it engulfed her hometown of Fabianum — sacrificing herself to save the young Augusta at Oak Hollow. Reborn as the legendary \"Fiend of Ever-Burning Flame,\" she took her new name from the Flame Demon Tacet Discord Galbrena she consumed. Now a Discord Slayer and consultant of the Black Shores, she hunts Tacet Discords across Solaris-3 with her Chimera, devouring their frequencies and powers.",
      kit: [
        "Dual Forte gauges: Echo Skills and her Resonance Skill fill Afterflame (red), while Basic Attacks and Intro fill Sinflame (purple).",
        "Forte Circuit: with both gauges charged she enters Demon Hypostasis, an enhanced state whose empowered Heavy Attacks (dealing Heavy Attack + Echo Skill DMG) carry ~70% of her total damage.",
        "Resonance Liberation: a large Fusion nuke that also raises the DMG multipliers of her transformed Demon Hypostasis abilities for 14s — roughly 20% of her damage and always cast before transforming.",
        "Intro Skill generates Sinflame; open with an Echo Skill immediately after switching in to start stacking Afterflame.",
        "Best single-target Fusion DPS in the game; her scaling lives in Heavy Attack DMG and Echo Skill DMG, not Basic Attack multipliers.",
      ],
      tips: [
        "Rotation: Intro > Echo Skill > Liberation > alternate Echo Skills (Afterflame) and Basic Attacks (Sinflame) > enter Demon Hypostasis and dump empowered Heavy Attacks.",
        "Always fire Liberation right before entering Demon Hypostasis so its 14s multiplier buff covers the whole burst window.",
        "Double Fusion DMG% on the 3-costs edges out ATK%+Fusion by about 2%; keep Heavy Attack DMG as a welcome substat after CRIT/ER/ATK%.",
        "Hit 110% Energy Regen minimum (120% is comfortable) or her Liberation won't be up every rotation and the burst loop falls apart.",
      ],
      synergies: [
        { id: "shorekeeper", why: "Best-in-slot support: Stellarealm grants team-wide CRIT and DMG buffs plus constant healing, letting Galbrena greed full offensive stats." },
        { id: "mornye", why: "Special synergy — lets Galbrena run a hypercarry setup while still enjoying mono-Fusion-tier buffing, the community's premium 3.5 pairing." },
        { id: "lynae", why: "Universal amplifier: 15% All-DMG Amp Outro and a 24% team DMG bonus from Prismatic Overblast slot cleanly into Galbrena hypercarry teams." },
      ],
    },
  },
  {
    id: "lynae",
    name: "Lynae",
    epithet: "Radiant Spectrum",
    element: "spectro",
    role: "Sub-DPS / Universal Buffer",
    weaponType: "Pistols",
    set: "5pc Pact of Neonlight Leap · Hyvatia main",
    setAlt: "5pc Rite of Gilded Revelation · 5pc Moonlit Clouds",
    weapon: "Spectrum Blaster",
    weaponAlt: "Phasic Homogenizer · Static Mist · Relativistic Jet · Solar Flame",
    talents: "Forte >> Liberation > Normal > Skill > Intro",
    stats: [
      { id: "main-4c", label: "4-Cost Main Stat", target: "CRIT Rate (or CRIT DMG)" },
      { id: "main-3c", label: "3-Cost Main Stats", target: "Spectro DMG% x2 (one ER% if rotations feel tight)" },
      { id: "main-1c", label: "1-Cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "60-70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "200-250%" },
      { id: "total-atk", label: "Total ATK", target: "2,000-2,200" },
      { id: "energy-regen", label: "Energy Regen", target: "120-125%" },
      { id: "substats", label: "Substat Priority", target: "CRIT > Basic Attack DMG > ATK% > ER" },
    ],
    note: "Do not overinvest in Energy Regen — she only needs ~120-125% to keep Prismatic Overblast cycling, and her buffs come from her kit, not her stats. Every point of ER past that (or an ER 3-cost main stat by default) is a common mistake that tanks her very real personal Basic Attack damage, which wants CRIT and ATK like a DPS.",
    altBuilds: [
      {
        id: "lynae-dps",
        label: "Personal DPS (Gilded Revelation)",
        role: "On-field Basic Attack Sub-DPS",
        set: "5pc Rite of Gilded Revelation",
        setAlt: "5pc Pact of Neonlight Leap",
        weapon: "Spectrum Blaster",
        weaponAlt: "Relativistic Jet · Solar Flame",
        talents: "Forte >> Normal > Liberation > Skill > Intro",
        stats: [
          { id: "dps-main-4c", label: "4-Cost Main Stat", target: "CRIT Rate or CRIT DMG (balance to ~1:2)" },
          { id: "dps-main-3c", label: "3-Cost Main Stats", target: "Spectro DMG% x2" },
          { id: "dps-main-1c", label: "1-Cost Main Stats", target: "ATK% x2" },
          { id: "dps-crit-rate", label: "CRIT Rate", target: "65-80%" },
          { id: "dps-crit-dmg", label: "CRIT DMG", target: "250-280%" },
          { id: "dps-total-atk", label: "Total ATK", target: "2,000+" },
          { id: "dps-energy-regen", label: "Energy Regen", target: "~110-120% (bare minimum)" },
          { id: "dps-substats", label: "Substat Priority", target: "CRIT > Basic Attack DMG > ATK%" },
        ],
        note: "Gilded Revelation stacks Spectro DMG through Basic Attacks and grants +40% Basic Attack DMG on Liberation cast, maximizing Kaleidoscopic Parade — but you give up the Neonlight Leap Outro ATK buff, so run this only when Lynae herself is the damage plan.",
      },
    ],
    deep: {
      lore: "Born a mercenary in the New Federation's Lawless Zone, she was hired to eliminate a Fractsidus operative named Lynae — and instead took the dying woman's Startorch Academy acceptance letter, faked her own death, and walked into a new life. The cold professional who once called anything that wasn't a weapon \"dead weight\" found friends, color, and belonging at the academy in Lahai-Roi, eventually re-enrolling under her own terms while keeping the name she had grown to love.",
      kit: [
        "Forte Circuit — Optical Sampling / Kaleidoscopic Parade: she builds Overflow in her default Optical Sampling stage, then Basic Attack: Spark Collision launches Kaleidoscopic Parade, an empowered pistol-barrage state where the bulk of her personal Spectro damage lives (it all counts as Basic Attack DMG).",
        "Resonance Skill — Lynae-Style Palettes / Additive Color (shared cooldown): quick Spectro pokes that feed Overflow and keep her rotation moving during quick swaps.",
        "Resonance Liberation — Prismatic Overblast: big Spectro burst that grants the WHOLE team +24% All DMG for 30s, and unlocks the follow-up Basic Attack \"To a Vivid Tomorrow!\", one of her hardest hits.",
        "Outro — Let's Hit the Road!: the next Resonator gets 15% All DMG Amplification and 25% Resonance Liberation DMG Amplification for 14s — element-agnostic, so she slots behind almost any main DPS.",
        "Her Tune Break / Tune Shifting debuff mechanic scales her team buffing (and her signature weapon's team DMG stacks), making her a rare universal amplifier who still posts serious sub-DPS numbers.",
        "With 5pc Pact of Neonlight Leap + Hyvatia, each Outro also hands the incoming DPS up to +30% ATK and +10% All-Attribute DMG — the swap itself becomes a damage steroid.",
      ],
      tips: [
        "Standard loop (~25s): Intro > Skill/Basics to build Overflow > Liberation > Kaleidoscopic Parade basic string > Outro into your main DPS while her 30s team buff keeps running.",
        "Always exit via Outro, not a raw swap — the 15%/25% amps, Neonlight Leap ATK buff, and Hyvatia bonus are all tied to the Outro cast.",
        "She is complete at S0 with one copy; Static Mist or Phasic Homogenizer get her close to signature performance, so she is genuinely F2P-friendly.",
        "Farm Pact of Neonlight Leap for team play; only run Rite of Gilded Revelation if you deliberately want a selfish personal-damage Lynae.",
      ],
      synergies: [
        { id: "cartethyia", why: "Her 25% Resonance Liberation DMG Amplification lands squarely on Cartethyia's Liberation-centric burst windows — one of the highest-value Outro pairings in the game." },
        { id: "augusta", why: "Lynae outbuffs a generic support slot in Augusta teams: their Outros chain into each other, and her element-free All DMG amp plus 24% team buff feed Augusta's huge Liberation hits." },
        { id: "shorekeeper", why: "Shorekeeper's healing and CRIT buffs stack cleanly with Lynae's ATK/DMG amps, forming the classic amp-plus-sustain backline behind any hypercarry." },
      ],
    },
  },
  {
    id: "shorekeeper",
    name: "Shorekeeper",
    epithet: "Guardian of the Black Shores",
    element: "spectro",
    role: "Support / Healer",
    weaponType: "Rectifier",
    set: "5pc Rejuvenating Glow · Fallacy of No Return main",
    setAlt: "5pc Moonlit Clouds · 2pc Rejuvenating Glow + 2pc Moonlit Clouds",
    weapon: "Stellar Symphony",
    weaponAlt: "Call of the Abyss (F2P craftable) · Variation (gacha 4★)",
    talents: "Skill = Intro > Liberation > Forte >> Basic",
    stats: [
      { id: "main-4c", label: "4-Cost Main Stat", target: "HP% (her own Crit does nothing — skip CRIT mains)" },
      { id: "main-3c", label: "3-Cost Main Stats", target: "Energy Regen% ×2 (swap one to HP% if ER-capped via Stellar Symphony)" },
      { id: "main-1c", label: "1-Cost Main Stats", target: "HP% ×2" },
      { id: "er-target", label: "Energy Regen", target: "250% total (230% is enough with Fallacy of No Return's +10% + her inherent +10%)" },
      { id: "hp-target", label: "Total HP", target: "~30,000+ (scales all her healing)" },
      { id: "crit-targets", label: "CRIT Rate / CRIT DMG", target: "Not needed — she grants the team up to +12.5% CR / +25% CD off her ER instead" },
      { id: "substats", label: "Substat Priority", target: "Energy Regen% > HP% > Flat HP > Healing Bonus" },
    ],
    note: "Do NOT build her with Crit or ATK: her party-wide Crit Rate/Crit DMG buff scales purely off her Energy Regen, capping at exactly 250% ER (12.5% CR / 25% CD) — anything past 250% is wasted, and anything under it is leaving free team Crit on the table. With the Fallacy of No Return echo and her inherent skill contributing ~20% ER, gearing to ~230% on the stat sheet is sufficient.",
    deep: {
      lore: "An enigmatic being who awoke in the Black Shores and became its guardian, the Shorekeeper is a constructed vessel who taught herself what it means to feel across countless cycles of watching over the Rover. Ageless and star-bound, she tends the boundary between dream and sea, her butterflies carrying fragments of memory across Solaris-3's tides.",
      kit: [
        "Resonance Skill (Chaos Theory): instantly heals the whole team and summons 5 Dim Star Butterflies that home in on enemies for Spectro DMG — her heals all scale off max HP.",
        "Resonance Liberation (End Loop): generates the Stellarealm, a large field that periodically heals active allies and grants Crit Rate/Crit DMG that scales with her Energy Regen — up to +12.5% CR / +25% CD at 250% ER.",
        "Forte Circuit: allied Intro Skills cast inside the field upgrade it twice (Inner → Supernal Stellarealm), boosting the Crit buffs and triggering her butterfly-form burst heal.",
        "Outro (Binary Butterfly): 15% All-Type DMG Amplification for the entire team for 30s that is NOT lost on swapping — usable by any DPS of any attribute.",
        "Her personal damage is negligible; 100% of her value is healing, ER-scaled Crit buffs, the all-type amp, and carrying the Rejuvenating Glow 15% team ATK buff.",
      ],
      tips: [
        "Hit the 250% ER breakpoint before anything else — Call of the Abyss (free craftable) or Variation (gacha 4★) plus the Fallacy of No Return echo gets you there comfortably without her signature weapon.",
        "Always Intro your DPS inside her Stellarealm: two Intro casts upgrade it to Supernal Stellarealm for the full Crit buff; a field that never gets upgraded is half a Liberation.",
        "Keep her rotation short: Intro → Skill → Echo → Liberation → Outro, then get your carry back on field; her buffs and Rejuvenating Glow ATK boost persist while she is off-field.",
        "She is the game's best Rejuvenating Glow carrier — her constant passive healing keeps the set's 15% team ATK buff at near-100% uptime.",
      ],
      synergies: [
        { id: "augusta", why: "Game8/Prydwen list Shorekeeper in every top Augusta team — her ER-scaled Crit buffs, all-type amp, and sustain slot straight into the Augusta hypercarry core." },
        { id: "phrolova", why: "The Augusta + Phrolova double-DPS comp runs Shorekeeper as its glue: Phrolova amps Heavy ATK damage off-field while Shorekeeper heals and feeds Crit to both." },
        { id: "hiyuki", why: "Crit-hungry Glacio carry — Shorekeeper's +12.5% CR/+25% CD can push a built Hiyuki past 100% Crit Rate while giving her team straightforward healing and energy support." },
      ],
    },
  },
  {
    id: "mornye",
    name: "Mornye",
    epithet: "Astral Mapping",
    element: "fusion",
    role: "Support / Healer",
    weaponType: "Broadblade",
    set: "5pc Halo of Starry Radiance · Reactor Husk main",
    setAlt: "5pc Rejuvenating Glow",
    weapon: "Starfield Calibrator",
    weaponAlt: "Discord · Broadblade#41 · Dauntless Evernight",
    talents: "Forte Circuit = Liberation > Skill > Intro > Basic",
    stats: [
      { id: "main-4c", label: "4-Cost Main Stat", target: "Healing Bonus (skip CRIT Rate/DMG mains)" },
      { id: "main-3c", label: "3-Cost Main Stats", target: "Energy Regen % ×2" },
      { id: "main-1c", label: "1-Cost Main Stats", target: "DEF% ×2" },
      { id: "er", label: "Energy Regen", target: "260% total (240% from gear; +10% passive, +10% Reactor Husk)" },
      { id: "lib-dmg", label: "Liberation DMG% (subs)", target: "Top damage substat once ER is capped" },
      { id: "crit-dmg", label: "CRIT DMG", target: "Filler after ER/Lib DMG — no fixed target" },
      { id: "crit-rate", label: "CRIT Rate", target: "Up to ~20% from subs, then stop — her Lib gains CRIT from ER" },
      { id: "def", label: "DEF% (subs)", target: "Stack after ER for bigger heals; DEF% > flat DEF" },
    ],
    note: "Every important number in her kit checks one stat: hit 260% Energy Regen before anything else — it maxes her Interfered Marker team amp (enemies take 40% more DMG) and feeds her Liberation's built-in CRIT conversion. Do not build her like a crit healer: Healing Bonus 4-cost and double ER 3-costs, with CRIT Rate capped around 20% from substats only.",
    deep: {
      lore: "A Spacetrek Collective researcher and professor of Exostrider Engineering at Lahai-Roi's Startorch Academy — brilliant, quiet, and unwavering in her dream to surpass the limits of spacetime and see the world beyond the sky. Born unable to walk due to underdeveloped lower spinal nerves, she strides on transparent neural-interface prosthetic legs, each step carrying her toward the stars.",
      kit: [
        "Resonance Skill heals the team, builds Concerto, and lays a Syntony Field granting interruption resistance and faster Off-Tune Buildup for Tune Break setups.",
        "Resonance Liberation upgrades it to a High Syntony Field (25s): +20% team DEF, +40% Healing Multiplier, and a Liberation hit that gains bonus CRIT stats scaling with her Energy Regen.",
        "Forte Circuit: Rest Mass Energy at 100 unlocks Heavy Attack – Geopotential Shift, launching her into mid-air Wide Area Observation Mode (30s) where she tags enemies with Observation Markers.",
        "When a marked enemy is Tune Break-ed, she applies an Interfered Marker (8s) — at 260% ER the team deals up to 40% more damage to it; this amp is where her real value lives.",
        "Intro Skill auto-triggers Wide Area Observation Mode for fast rotations; Outro grants the whole team a 25% DMG increase.",
        "Her personal damage is minor (mostly the Liberation hit) — she is a Shorekeeper-tier buffer whose output is measured in team amps and heals.",
      ],
      tips: [
        "Rush 260% ER before touching anything else — ER weapon (77% on Starfield Calibrator), double ER 3-costs, and Reactor Husk's passive 10% get you there.",
        "Swap her in via Intro Skill: it auto-enters Wide Area Observation Mode, saving the Rest Mass Energy ramp and speeding up rotations.",
        "Heal on purpose before your DPS window — Halo of Starry Radiance converts her heals into up to 25% team ATK, stacking with her 25% Outro amp.",
        "In Tune Break teams, drop Observation Markers first, then let the team Tune Break the target so the 40% Interfered Marker amp covers your burst.",
      ],
      synergies: [
        { id: "lynae", why: "Her premier partner: Mornye's Off-Tune Buildup boost and Interfered Marker amp let Lynae trigger Tune Break loops far more often in the game's top Tune Rupture teams." },
        { id: "luuk-herssen", why: "A Tune Rupture/Strain applier whose procs Mornye can respond to, converting his pressure into a team-wide 40% DMG amp via Interfered Marker." },
        { id: "galbrena", why: "In mono-Fusion lineups Mornye's generalist heals, 25% Outro amp, and team ATK from her set slot straight under the strongest Fusion carry." },
      ],
    },
  },
  {
    id: "ciaccona",
    name: "Ciaccona",
    epithet: "Wandering Bard of Rinascita",
    element: "aero",
    role: "Support",
    weaponType: "Pistols",
    set: "5pc Gusts of Welkin · Reminiscence: Fleurdelys main",
    setAlt: "5pc Moonlit Clouds (Frazzle teams) · 5pc Windward Pilgrimage",
    weapon: "Woodland Aria",
    weaponAlt: "Phasic Homogenizer · Static Mist · Cadenza · Relativistic Jet",
    talents: "Liberation >> Forte Circuit ≈ Basic Attack > Skill > Intro",
    stats: [
      { id: "cost4-main", label: "4-cost Main Stat", target: "CRIT Rate (or CRIT DMG — take the one opposite your weapon's crit substat)" },
      { id: "cost3-main", label: "3-cost Main Stats", target: "Aero DMG% x2 (swap one for Energy Regen if ER substats are short)" },
      { id: "cost1-main", label: "1-cost Main Stats", target: "ATK% x2" },
      { id: "crit-rate", label: "CRIT Rate", target: "60-70%" },
      { id: "crit-dmg", label: "CRIT DMG", target: "180-230% (keep ~1:2 ratio)" },
      { id: "energy-regen", label: "Energy Regen", target: "~150% (mainstream range 140-160%)" },
      { id: "total-atk", label: "Total ATK", target: "1,700-2,000+" },
      { id: "substats", label: "Substat Priority", target: "CRIT Rate/DMG > Energy Regen > ATK% > Liberation DMG / Heavy ATK DMG" },
    ],
    note: "Despite the Support tag, Ciaccona is built like a crit sub-DPS — the most common mistake is skipping Energy Regen for pure crit. Without roughly 150% ER her Resonance Liberation concert (where most of her damage and Aero Erosion application lives) is not up every rotation, and everything downstream of her buffs falls apart.",
    altBuilds: [
      {
        id: "frazzle-support",
        label: "Spectro Frazzle Enabler",
        role: "Off-field Frazzle applier / Outro buffer",
        set: "5pc Moonlit Clouds",
        setAlt: "5pc Gusts of Welkin",
        weapon: "Cadenza",
        weaponAlt: "Static Mist · Woodland Aria",
        talents: "Liberation >> Forte Circuit > Intro",
        stats: [
          { id: "fz-cost4", label: "4-cost Main Stat", target: "CRIT Rate (ER main acceptable on budget)" },
          { id: "fz-cost3", label: "3-cost Main Stats", target: "Energy Regen + Aero DMG% (or ATK%)" },
          { id: "fz-cost1", label: "1-cost Main Stats", target: "ATK% x2" },
          { id: "fz-er", label: "Energy Regen", target: "140-160% (ER first, damage second)" },
          { id: "fz-crit", label: "CRIT Rate", target: "50%+ (comfort target; her personal DMG matters less here)" },
        ],
        note: "With Spectro teammates her concert applies Spectro Frazzle instead of Aero Erosion; Moonlit Clouds converts her fast Outro cycle into a 22.5% ATK buff for the incoming carry, so ER and rotation speed outrank her own crit.",
      },
    ],
    deep: {
      lore: "A free-spirited bard wandering Rinascita in search of inspiration, Ciaccona turns the tales she gathers — of saints, heroes, miracles and farewells — into songs performed for commoners and Divinity alike. Her name comes from the ciaccona (chaconne), a Baroque musical form, and she fights the way she lives: conducting the wind itself, flanked by her Ensemble Sylphs.",
      kit: [
        "Resonance Skill — Improvisation: performs a Symphonic Poem with her Ensemble Sylphs, then enters Recital, a rhythm mini-game where timing inputs to the radiating sound waves generates Symphonic Poem Tonics and refunds Concerto Energy.",
        "Resonance Liberation: starts a concert performance that stacks Aero Erosion on enemies; her sylphs keep playing after she swaps out, making her a premier off-field Aero Erosion applier with zero field-time cost.",
        "Forte Circuit: banks up to 3 segments of Musical Essence (recovered via Basic Attack stage 4 and Intro Skill) to fire an Enhanced Heavy Attack — a giant golden note that deals big Aero DMG and vacuums enemies together.",
        "Team-adaptive gimmick: with Spectro teammates her performance applies Spectro Frazzle instead of Aero Erosion, which is why she moonlights as the best enabler in Frazzle teams too.",
        "Outro Skill: 100% Aero Erosion DMG Deepen for 30s — the single biggest amplification an Aero Erosion carry can receive.",
        "Where the damage lives: off-field Liberation concert ticks + the Enhanced Heavy Attack, both ATK/crit scaling — hence real crit investment on a 'support'.",
      ],
      tips: [
        "Rotation: build Musical Essence, fire the Enhanced Heavy, cast Liberation, then swap — the concert persists off-field, so never sit on the field with her longer than needed.",
        "Match the 4-cost crit main stat to complement your weapon: Woodland Aria/Phasic Homogenizer carry a crit substat, so take the opposite crit stat on the 4-cost.",
        "Nightmare: Kelpie is virtually tied with Reminiscence: Fleurdelys as her main echo — equip whichever copy rolled better substats.",
        "If ER substats aren't cooperating, run one Energy Regen 3-cost instead of double Aero DMG% — Liberation uptime beats a few percent of Aero damage.",
      ],
      synergies: [
        { id: "cartethyia", why: "The defining pairing: Ciaccona's 100% Aero Erosion DMG Deepen Outro plus constant off-field Erosion stacking is exactly what the game's premier Aero Erosion DPS scales off — she is Cartethyia's best-in-slot partner." },
        { id: "shorekeeper", why: "Universal third slot: Shorekeeper's healing, concerto battery and team-wide crit/ATK amplification stack cleanly on top of Ciaccona's element-specific buffs when you lack a dedicated Aero support." },
      ],
    },
  },
];

export const ATTRIBUTE_ORDER = ["glacio", "fusion", "electro", "aero", "spectro", "havoc"];
