import RegionQuestTracker from "./RegionQuestTracker";

/* ============================================================
   INAZUMA QUEST DATA
   World Quests + Story Quests + Hangouts that reward primogems.
   Archon Quests intentionally excluded per scope.
   Sources: Game8, Fandom Wiki, GameWith (cross-checked May 2026).
   ============================================================ */

const tiers = [
  { id:1, label:"Tier 1", sublabel:"Very Fast",    time:"5-15 min",  color:"#93c5fd", bg:"rgba(147,197,253,0.07)", border:"rgba(147,197,253,0.22)", glow:"rgba(147,197,253,0.12)", icon:"⚡" },
  { id:2, label:"Tier 2", sublabel:"Short",        time:"15-30 min", color:"#67e8f9", bg:"rgba(103,232,249,0.07)", border:"rgba(103,232,249,0.22)", glow:"rgba(103,232,249,0.12)", icon:"⛩" },
  { id:3, label:"Tier 3", sublabel:"Medium",       time:"30-60 min", color:"#a5b4fc", bg:"rgba(165,180,252,0.07)", border:"rgba(165,180,252,0.22)", glow:"rgba(165,180,252,0.12)", icon:"⚖" },
  { id:4, label:"Tier 4", sublabel:"Long / Gated", time:"60 min+",   color:"#c4b5fd", bg:"rgba(196,181,253,0.07)", border:"rgba(196,181,253,0.22)", glow:"rgba(196,181,253,0.12)", icon:"🌸" },
];

const chainTags = {
  story:      { label:"Story Quest",       color:"#06b6d4" },
  hangout:    { label:"Hangout Event",     color:"#ec4899" },
  sakura:     { label:"Sacred Sakura",     color:"#f472b6" },
  mists:      { label:"Through the Mists", color:"#a78bfa" },
  orobashi:   { label:"Orobashi's Legacy", color:"#10b981" },
  enkanomiya: { label:"Enkanomiya",        color:"#0ea5e9" },
  tatara:     { label:"Tatara Tales",      color:"#f59e0b" },
  standalone: { label:"Standalone",        color:"#64748b" },
  gourmet:    { label:"Gourmet Supremos",  color:"#f97316" },
  commission: { label:"Commission-Locked", color:"#94a3b8" },
  seirai:     { label:"Seirai Island",     color:"#0ea5e9" },
};

const quests = [
  { id:1, tier:1, chain:"sakura", name:"A Strange Story in Konda", time:"10-15 min", region:"Narukami Island — Konda Village", activate:"Talk to the village chief in Konda Village (south of the Grand Narukami Shrine).", prereqs:"AQ Chapter II Act I 'The Immovable God and the Eternal Euthymia' completed", notes:"Gate quest into the Sacred Sakura Cleansing Ritual chain. Pure investigation; ends with a small Hydro/Electro puzzle.", rewards:"40 Primogems · Adv EXP · Mora · gateway to the Sacred Sakura chain", game8:"https://game8.co/games/Genshin-Impact/archives/337735" },
  { id:2, tier:1, chain:"standalone", name:"Saga of Mr. Forgetful", time:"10-15 min", region:"Inazuma City", activate:"Find the forgetful NPC Yota wandering in Inazuma City; he asks for help re-finding what he's lost.", prereqs:"Inazuma City accessible", notes:"Short, comedic series of quick item retrievals. Multiple sub-quests but each is fast.", rewards:"Primogems · Adv EXP · Mora (per sub-quest)", fandom:"https://genshin-impact.fandom.com/wiki/Saga_of_Mr._Forgetful" },
  { id:3, tier:1, chain:"standalone", name:"Ritou Escape Plan (World Quest)", time:"10-15 min", region:"Ritou (entry port to Inazuma)", activate:"Auto-triggers after completing the Ritou Escape Plan Archon Quest. Liben (the Liyue merchant) starts the world-quest version.", prereqs:"AQ Chapter II Act I 'Ritou Escape Plan' completed", notes:"Liben follow-up. He needs odds and ends from around Ritou; quick fetch chain.", rewards:"Primogems · Adv EXP · Mora", fandom:"https://genshin-impact.fandom.com/wiki/Ritou_Escape_Plan_(Quest_Series)" },

  { id:4, tier:2, chain:"standalone", name:"Gourmet Supremos, Assemble!", time:"15-20 min", region:"Inazuma City — Komore Teahouse area", activate:"Talk to Xudong (Wanmin Restaurant chef visiting from Liyue).", prereqs:"Inazuma City accessible", notes:"Xudong needs exotic Inazuma ingredients including a 'zapped' Sakura Bloom. Quick cooking quest with primogems.", rewards:"Primogems · Adv EXP · Mora · 'Heart of Liyue, Soul of Inazuma' achievement", fandom:"https://genshin-impact.fandom.com/wiki/Gourmet_Supremos,_Assemble!" },
  { id:5, tier:2, chain:"standalone", name:"The Farmer's Treasure", time:"15-25 min", region:"Narukami Island — Konda Village area", activate:"Talk to Sanzou the farmer near Konda Village; he asks help guarding his crops.", prereqs:"Narukami Island accessible", notes:"Defend the farm, then investigate a 'treasure' on the back hill. Simple combat + puzzle.", rewards:"Primogems · Adv EXP · Mora", fandom:"https://genshin-impact.fandom.com/wiki/The_Farmer's_Treasure" },
  { id:6, tier:2, chain:"standalone", name:"Cleansing Defilement", time:"20-30 min", region:"Yashiori Island — Tatarasuna", activate:"Approach the Tatarigami contamination zones in Tatarasuna. Each cluster has a Mikoshi to cleanse.", prereqs:"Yashiori Island accessible (after AQ Ch II Act II 'Stillness, the Sublimation of Shadow')", notes:"Solve four Mikoshi puzzles (purification mechanic). Reduces ambient Electro corrosion in the area afterwards.", rewards:"Primogems · Adv EXP · Mora · removes Electro corrosion damage in cleansed zones", fandom:"https://genshin-impact.fandom.com/wiki/Cleansing_Defilement" },
  { id:7, tier:2, chain:"orobashi", name:"Orobashi's Legacy: Prologue", time:"20-30 min", region:"Yashiori Island — Fort Fujitou", activate:"Talk to Kaji at Fort Fujitou on Yashiori Island.", prereqs:"AQ Chapter II Act I 'Ritou Escape Plan' completed", notes:"Opens the Orobashi's Legacy chain (Prologue → Part I → II → III → Epilogue). Pull the broken arrow free with a Cryo character. Each subsequent part gives more primogems.", rewards:"20 Primogems (Prologue) · 10,000 Mora · unlocks Part I (40 primo · 30,000 Mora · 4 Hero's Wit)", mora: 10000, game8:"https://game8.co/games/Genshin-Impact/archives/338688" },

  { id:8, tier:3, chain:"sakura", name:"Sacred Sakura Cleansing Ritual", time:"45-60 min (full chain across multiple sittings)", region:"Narukami Island — Grand Narukami Shrine", activate:"Talk to Inagi Hotomi at the Grand Narukami Shrine after A Strange Story in Konda is done.", prereqs:"A Strange Story in Konda completed · AQ Ch II Act I", notes:"Cleanse all the Electro corruption nodes scattered across Narukami Island by placing Electrograna at the Sakura's roots. Multi-step chain (Cleansing the Defilement, Word on the Wisps, etc.). The total primogem haul across the chain is huge.", rewards:"~180 Primogems total · 160,000 Mora · 14 Mystic Enhancement Ore · 16 Hero's Wit · 1 Mask of Memories · 1 Memento Lens", mora: 160000, heroWit: 16, fandom:"https://genshin-impact.fandom.com/wiki/Sacred_Sakura_Cleansing_Ritual" },
  { id:9, tier:3, chain:"standalone", name:"The Moon-Bathed Deep", time:"45-60 min", region:"Watatsumi Island — Bourou Village + Suigetsu Pool", activate:"Talk to Hyouta at Suigetsu Pool on Watatsumi Island. He needs help retrieving items from the pool's depths.", prereqs:"Watatsumi Island accessible (after AQ Ch II Act II)", notes:"Underwater (well, pool-bottom) exploration chain. Sets up the Watatsumi-side Orobashi lore. Multi-act with a few combat encounters.", rewards:"Primogems · Adv EXP · Mora · Hero's Wit · Mystic Enhancement Ore", fandom:"https://genshin-impact.fandom.com/wiki/The_Moon-Bathed_Deep" },
  { id:10, tier:3, chain:"story", name:"Kazuha — A Strange and Friendless Road", time:"45-60 min", region:"Inazuma City → Yashiori Island", activate:"Story Quest menu. Spend 1 Story Key. Find Kazuha at the harbor.", prereqs:"AR 40 + AQ Ch II Act III 'Omnipresence Over Mortals' + Raiden's Story Act I (Reflections of Mortality) + 1 Story Key", notes:"Acer Palmatum Chapter — Act I. Kazuha returns to settle business with his former master. Heavily story-driven, with one significant combat sequence.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Kazuha ascension materials", mora: 26925, heroWit: 3, game8:"https://game8.co/games/Genshin-Impact/archives/332836" },
  { id:11, tier:3, chain:"story", name:"Yoimiya — Star-Pickers' Passage", time:"45-60 min", region:"Inazuma City — Hanamizaka", activate:"Story Quest menu. Spend 1 Story Key. Find Yoimiya at Naganohara Fireworks (Hanamizaka).", prereqs:"AR 40 + AQ Ch II Act I + 1 Story Key", notes:"Carassius Auratus Chapter — Act I. Help Yoimiya make a child's wish come true. The combat is light; the writing is unusually tender for a 5★ Story Quest.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Yoimiya ascension materials", mora: 26925, heroWit: 3, fandom:"https://genshin-impact.fandom.com/wiki/Carassius_Auratus_Chapter" },
  { id:12, tier:3, chain:"story", name:"Ayato — The Firmiana Leaf Falls", time:"45-60 min", region:"Inazuma City — Kamisato Estate", activate:"Story Quest menu. Spend 1 Story Key. Find Thoma at Kamisato Estate; he forwards you to Ayato.", prereqs:"AR 40 + AQ Ch II Act III + 1 Story Key", notes:"Cypressus Custos Chapter — Act I. Ayato pulls you into a domestic-politics maneuver involving the Yashiro Commission. Mostly dialogue + one significant set-piece fight.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Ayato ascension materials", mora: 26925, heroWit: 3, fandom:"https://genshin-impact.fandom.com/wiki/Cypressus_Custos_Chapter" },
  { id:13, tier:3, chain:"story", name:"Kokomi — Warriors' Dreams Like Spring Grass Renewing", time:"45-60 min", region:"Watatsumi Island — Sangonomiya Shrine", activate:"Story Quest menu. Spend 1 Story Key. Find Kokomi at Sangonomiya Shrine.", prereqs:"AR 40 + AQ Ch II Act II (Stillness, the Sublimation of Shadow) + 1 Story Key", notes:"Dracaena Somnolenta Chapter — Act I. Kokomi takes you on a tour of Watatsumi (Watatsumi Sightseeing → Her Secret → New Beginning). Reveals a lot of Watatsumi's post-war state.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Kokomi ascension materials", mora: 26925, heroWit: 3, game8:"https://game8.co/games/Genshin-Impact/archives/340683" },
  { id:14, tier:3, chain:"story", name:"Itto — Rise Up, Golden Soul", time:"45-60 min", region:"Inazuma City → Konda Village", activate:"Story Quest menu. Spend 1 Story Key. Find Itto at the Hanamizaka entrance.", prereqs:"AR 40 + Kokomi's Story Quest (Warriors' Dreams Like Spring Grass Renewing) + 1 Story Key", notes:"Taurus Iracundus Chapter — Act I. Itto's signature beetle tournament; loud, funny, and surprisingly heartfelt under the chaos.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Itto ascension materials", mora: 26925, heroWit: 3, game8:"https://game8.co/games/Genshin-Impact/archives/349460" },

  { id:15, tier:4, chain:"mists", name:"Through the Mists", time:"2-3 hours (full chain, Tsurumi Island)", region:"Tsurumi Island (perpetually fogged)", activate:"Talk to Katheryne in Inazuma City for the 'A Particularly Particular Author' commission; that leads onto Tsurumi.", prereqs:"AR 30 + AQ Ch II Act III 'Omnipresence Over Mortals' + 'A Particularly Particular Author' world quest accepted", notes:"The Tsurumi Island opening chain. Includes Octave of the Maushiro (where you receive the Peculiar Pinion gadget that unlocks treasure cages across the island). Fog only lifts as quest steps progress — don't try Tsurumi exploration without starting this.", rewards:"~180 Primogems total · 160,000 Mora · 16 Mystic Enhancement Ore · 20 Hero's Wit · Peculiar Pinion gadget · Maushiro gadget", mora: 160000, heroWit: 20, fandom:"https://genshin-impact.fandom.com/wiki/Through_the_Mists" },
  { id:16, tier:4, chain:"enkanomiya", name:"Three Realms Gateway Offering: Aftermath", time:"60-90 min (full chain after event integration)", region:"Enkanomiya — across all districts", activate:"Talk to Aru / Tsuyuko at the Enkanomiya entrance after the event's permanent integration in v2.5+.", prereqs:"AR 30 + AQ Ch II Act II + 'Erebos' Secret' world quest (Enkanomiya gate) completed", notes:"Originally a 2.5 Flagship Event, now a permanent Enkanomiya world quest chain. Multi-part: Three Realms Gateway Offering: Part 1 / 2 / 3 / Aftermath. The achievement quest 'Erebos' Secret' is the unlock prerequisite.", rewards:"Primogems · Adv EXP · Mora · Hero's Wit · Mystic Enhancement Ore", game8:"https://game8.co/games/Genshin-Impact/archives/360609" },
  { id:17, tier:4, chain:"story", name:"Raiden I — Reflections of Mortality", time:"60-90 min", region:"Inazuma City → Tenshukaku", activate:"Story Quest menu. Spend 1 Story Key. Talk to Kujou Sara at the Tenshukaku entrance.", prereqs:"AR 40 + AQ Ch II Act III 'Omnipresence Over Mortals' + 1 Story Key", notes:"Imperatrix Umbrosa Chapter — Act I. The Shogun returns to the dueling ground. Long Story Quest with major lore reveals about Ei and the Plane of Euthymia.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Raiden Shogun ascension materials", mora: 26925, heroWit: 3, game8:"https://game8.co/games/Genshin-Impact/archives/340682" },
  { id:18, tier:4, chain:"story", name:"Raiden II — Transient Dreams", time:"60-90 min", region:"Inazuma City → Plane of Euthymia", activate:"Story Quest menu. Spend 1 Story Key. Pick up from the Tenshukaku after the v2.5 unlock.", prereqs:"AR 40 + Reflections of Mortality (Act I) + AQ Ch II Act III + 1 Story Key (released v2.5)", notes:"Imperatrix Umbrosa Chapter — Act II. Ei wrestles with Makoto's shadow and her sense of duty. Long, almost entirely cutscene.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit", mora: 26925, heroWit: 3, game8:"https://game8.co/games/Genshin-Impact/archives/356368" },
  { id:19, tier:4, chain:"story", name:"Ayaka — The Whispers of the Crane and the White Rabbit", time:"60-90 min", region:"Inazuma City — Kamisato Estate", activate:"Story Quest menu. Spend 1 Story Key. Find Thoma at Kamisato Estate to be forwarded to Ayaka.", prereqs:"AR 40 + AQ Ch II Act III + 1 Story Key", notes:"Grus Nivis Chapter — Act I. A multi-quest arc (The Whispers of the Crane and the White Rabbit → A Private Commission → Woven Wishes → Food From Afar → Lasting Promise → With You). Slow, intimate, lots of dialogue.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Ayaka ascension materials", mora: 26925, heroWit: 3, fandom:"https://genshin-impact.fandom.com/wiki/Grus_Nivis_Chapter" },
  { id:20, tier:4, chain:"story", name:"Yae Miko — Tales of Two Foxes", time:"60-90 min", region:"Narukami Island — Grand Narukami Shrine", activate:"Story Quest menu. Spend 1 Story Key. Yae Miko summons you to the Shrine.", prereqs:"AR 40 + Reflections of Mortality + Acer Palmatum Act I (Kazuha) + Transient Dreams + 1 Story Key (heavily gated)", notes:"Divina Vulpes Chapter — Act I. Yae Miko sets you to tracking down some half-truths in Inazuma. Heavily story-driven, often considered one of the best-written 5★ Story Quests in the game.", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Yae Miko ascension materials", mora: 26925, heroWit: 3, fandom:"https://genshin-impact.fandom.com/wiki/Divina_Vulpes_Chapter" },
  { id:21, tier:4, chain:"hangout", name:"Sayu — Yoohoo Art: Seichou no Jutsu", time:"60-90 min (all endings)", region:"Inazuma City — Shiyuumatsu-Ban roof", activate:"Hangout menu. Spend 2 Story Keys per playthrough. Find Sayu on the Shiyuumatsu-Ban rooftop in Inazuma City.", prereqs:"AR 26 + Prologue Ch III + Story Keys", notes:"Released v2.2 (first Inazuma Hangout). Five endings; multiple playthroughs needed for full primogem haul.", rewards:"~90 Primogems total (60 endings + 30 achievements) · Special Dish · Adv EXP · Hero's Wit · Sayu ascension materials", heroWit: 4, fandom:"https://genshin-impact.fandom.com/wiki/Hangout_Event/Sayu" },
  { id:22, tier:4, chain:"hangout", name:"Thoma — A Housekeeper's Daily Chores", time:"60-90 min (all endings)", region:"Inazuma City — Kamisato Estate", activate:"Hangout menu. Spend 2 Story Keys per playthrough. Find Thoma at Kamisato Estate.", prereqs:"AR 26 + Prologue Ch III + Story Keys", notes:"Released v2.2 alongside Sayu. Multi-ending; comedy + slice-of-life Kamisato Estate vignettes.", rewards:"~90 Primogems total · Special Dish · Adv EXP · Hero's Wit · Thoma ascension materials", heroWit: 4, fandom:"https://genshin-impact.fandom.com/wiki/Hangout_Event/Thoma" },
  { id:23, tier:4, chain:"hangout", name:"Gorou — The Canine General's Special Operations", time:"60-90 min (all endings)", region:"Watatsumi Island — Sangonomiya Shrine area", activate:"Hangout menu. Spend 2 Story Keys per playthrough. Find Gorou near Sangonomiya Shrine.", prereqs:"AR 26 + Prologue Ch III + AQ Ch II Act II (Stillness, the Sublimation of Shadow) + Story Keys", notes:"Released v2.3. Multi-ending; Watatsumi reconstruction logistics framed as a Gorou sortie.", rewards:"~90 Primogems total · Special Dish · Adv EXP · Hero's Wit · Gorou ascension materials", heroWit: 4, fandom:"https://genshin-impact.fandom.com/wiki/Hangout_Event/Gorou" },
  { id:24, tier:4, chain:"hangout", name:"Shikanoin Heizou — Trap 'Em by Storm", time:"60-90 min (all endings)", region:"Inazuma City — Tenryou Commission HQ", activate:"Hangout menu. Spend 2 Story Keys per playthrough. Find Heizou near the Tenryou Commission building.", prereqs:"AR 26 + Prologue Ch III + Story Keys (Heizou released v2.8)", notes:"Released v2.8. Six endings; detective mystery framing — Heizou investigates a string of petty crimes that turn out connected.", rewards:"~90 Primogems total · Special Dish · Adv EXP · Hero's Wit · Heizou ascension materials", heroWit: 4, game8:"https://game8.co/games/Genshin-Impact/archives/381345" },
  { id:25, tier:4, chain:"tatara", name:"Tatara Tales (Full Chain)", time:"2-3 hours (real-time gated across multiple days)", region:"Tatarasuna — Mikage Furnace", activate:"Talk to Xavier at the Mikage Furnace camp in Tatarasuna.", prereqs:"Inazuma accessible · Yashiori Island reachable", notes:"Multi-day real-time-gated chain (must wait 24 hours between some steps). Clears Tatarasuna's Balethunder zone permanently. The 225k Mora total makes this the single highest Mora-per-quest in Inazuma — but the real-time gating means you should START it early and let it progress over days.", rewards:"225,000 Mora · 7 Hero's Wit · Blueprint: Square Yumemiru Stool · Adv EXP", mora: 225000, heroWit: 7, fandom:"https://genshin-impact.fandom.com/wiki/Tatara_Tales" },
];

const orderNote = [
  { step:1, text:"Quick wins first: A Strange Story in Konda (gates Sacred Sakura, 10 min), Saga of Mr. Forgetful, Gourmet Supremos. All under 15 min each." },
  { step:2, text:"Sacred Sakura Cleansing Ritual is one of the biggest single primogem hauls in the game (~180). Bundle it with the rest of Narukami Island exploration." },
  { step:3, text:"Yashiori Island block: do Cleansing Defilement first (it makes the island safer to walk), then start Orobashi's Legacy: Prologue and chain through its Parts." },
  { step:4, text:"Through the Mists (Tsurumi Island) is gated by 'A Particularly Particular Author'. Don't go to Tsurumi for exploration without starting this chain — the fog is unsolvable otherwise." },
  { step:5, text:"Story Quest order is heavily gated: Raiden I → Kazuha (needs Raiden I + AQ Ch II Act III) → Raiden II → Yae Miko (needs Raiden II + Kazuha). Itto needs Kokomi's Story Quest done first." },
  { step:6, text:"Enkanomiya's 'Erebos' Secret' is the entry world quest; finish it to unlock the Three Realms Gateway Offering chain (originally a 2.5 event, now permanent)." },
  { step:7, text:"Hangouts cost 2 Story Keys per playthrough × multiple endings each. Save them for after the Story Quests — each Story Quest is a one-shot 60-primo unlock." },
];

const config = {
  title: "Inazuma World Quests",
  subtitleLabel: "World Quests · Story Quests · Hangouts — primogems, Mora & Hero's Wit",
  logoEmoji: "⛩",
  completeEmoji: "⛩✨",
  completeTitle: "ALL INAZUMA QUESTS COMPLETE",
  completeMessage: "Eternity sees you, Traveler. The Shogun acknowledges your devotion.",
  storageKey: "inazuma-quest-tracker-v1",
  tiers, chainTags, quests, orderNote,
  theme: {
    pageBg:           "linear-gradient(160deg,#0a0418 0%,#1c0d3a 40%,#2a155a 100%)",
    headerBg:         "rgba(5,2,15,0.97)",
    pattern1:         "rgba(196,181,253,0.06)",
    pattern2:         "rgba(139,92,246,0.06)",
    cardBg:           "linear-gradient(135deg,rgba(20,10,40,0.92),rgba(14,6,28,0.92))",
    logoBg:           "linear-gradient(135deg,#8b5cf6,#3b0764)",
    titleGradient:    "linear-gradient(135deg,#f5f3ff 0%,#c4b5fd 50%,#7c3aed 100%)",
    progressGradient: "linear-gradient(90deg,#5b21b6,#8b5cf6,#c4b5fd)",
    textPrimary:      "#ede9fe",
    textBright:       "#f5f3ff",
    textRgb:          [237, 233, 254],
    accent:           "#c4b5fd",
    accentRgb:        [196, 181, 253],
  },
};

export default function InazumaQuests() {
  return <RegionQuestTracker config={config} />;
}
