import RegionQuestTracker from "./RegionQuestTracker";

/* ============================================================
   NATLAN QUEST DATA
   World Quests + Tribal Chronicles + Story Quests + Hangouts
   that reward primogems. Archon Quests intentionally excluded.
   Sources: Game8, Fandom Wiki, GameWith (cross-checked May 2026).
   ============================================================ */

const tiers = [
  { id:1, label:"Tier 1", sublabel:"Very Fast",    time:"5-15 min",  color:"#93c5fd", bg:"rgba(147,197,253,0.07)", border:"rgba(147,197,253,0.22)", glow:"rgba(147,197,253,0.12)", icon:"🔥" },
  { id:2, label:"Tier 2", sublabel:"Short",        time:"15-30 min", color:"#67e8f9", bg:"rgba(103,232,249,0.07)", border:"rgba(103,232,249,0.22)", glow:"rgba(103,232,249,0.12)", icon:"🪶" },
  { id:3, label:"Tier 3", sublabel:"Medium",       time:"30-60 min", color:"#a5b4fc", bg:"rgba(165,180,252,0.07)", border:"rgba(165,180,252,0.22)", glow:"rgba(165,180,252,0.12)", icon:"⚖" },
  { id:4, label:"Tier 4", sublabel:"Long / Gated", time:"60 min+",   color:"#c4b5fd", bg:"rgba(196,181,253,0.07)", border:"rgba(196,181,253,0.22)", glow:"rgba(196,181,253,0.12)", icon:"🌋" },
];

const chainTags = {
  story:      { label:"Story Quest",       color:"#06b6d4" },
  hangout:    { label:"Hangout Event",     color:"#ec4899" },
  tribal:     { label:"Tribal Chronicle",  color:"#f59e0b" },
  saurian:    { label:"Saurian Companion", color:"#22c55e" },
  standalone: { label:"Standalone",        color:"#64748b" },
  footsteps:  { label:"Footsteps Chain",   color:"#22c55e" },
  hidden:     { label:"Hidden Quest",      color:"#a78bfa" },
  easybreeze: { label:"Easybreeze Resort", color:"#fb923c" },
};

const quests = [
  { id:1, tier:1, chain:"standalone", name:"Natlan! A New Adventure", time:"10-15 min", region:"Natlan — entry portal → Stadium of the Sacred Flame", activate:"Auto-triggers upon entering Natlan via the AQ entry. The opening quest of the region.", prereqs:"AR 30+ · AQ Sumeru completed · entry to Natlan via AQ Ch V Act I", notes:"Pulls you to the Stadium of the Sacred Flame and introduces the Saurian companion mechanic. Required gateway to most other Natlan content.", rewards:"Primogems · Saurian companion intro · Adv EXP · Mora", game8:"https://game8.co/games/Genshin-Impact/archives/470215" },
  { id:2, tier:1, chain:"saurian", name:"Lost in the Woods", time:"10-15 min", region:"Coatepec Mountain area", activate:"Find the wandering Tepetlisaur near Coatepec Mountain.", prereqs:"Natlan accessible", notes:"First sub-quest of the Between Pledge and Forgettance series. You meet the saurian later named 'Little One' here.", rewards:"Primogems · Adv EXP · Mora · unlocks Little One follow-up", game8:"https://game8.co/games/Genshin-Impact/archives/408476" },
  { id:3, tier:1, chain:"saurian", name:"Little One (Tepetlisaur Naming)", time:"5-10 min", region:"Coatepec Mountain (continues from Lost in the Woods)", activate:"Continues from Lost in the Woods. Pick a name for your saurian companion.", prereqs:"Lost in the Woods completed", notes:"Naming ceremony — the chosen name persists in all later Natlan dialogue. Pick deliberately.", rewards:"Primogems · named Saurian companion · achievement", fandom:"https://genshin-impact.fandom.com/wiki/Little_One" },

  { id:4, tier:2, chain:"tribal", name:"Tribal Chronicles — Scions of the Canopy", time:"20-30 min", region:"Toyac Springs · Scions of the Canopy territory", activate:"Talk to the Tribal Chieftain after reaching the Scions of the Canopy area.", prereqs:"Natlan unlocked (AQ Ch V Act I)", notes:"Kinich + Ajaw's home tribe. Tribe Reputation EXP + crafting / domain unlocks here.", rewards:"Primogems · Adv EXP · Mora · Tribe Reputation EXP · crafting unlocks", fandom:"https://genshin-impact.fandom.com/wiki/Scions_of_the_Canopy" },
  { id:5, tier:2, chain:"tribal", name:"Tribal Chronicles — Children of Echoes", time:"20-30 min", region:"Coatepec Mountain · Children of Echoes territory", activate:"Tribal Chronicles menu. Talk to the liaison in the tribe's plaza.", prereqs:"Natlan unlocked", notes:"Xilonen's tribe (the smiths). Gear-tuning bench and saurian-related crafting unlocks here.", rewards:"Primogems · Adv EXP · Mora · Tribe Reputation EXP · gear-tuning bench unlocks", fandom:"https://genshin-impact.fandom.com/wiki/Children_of_Echoes" },
  { id:6, tier:2, chain:"tribal", name:"Tribal Chronicles — People of the Springs", time:"20-30 min", region:"Tequemecan Valley · People of the Springs territory", activate:"Tribal Chronicles menu. Talk to Mualani or her relatives near the Springs.", prereqs:"Natlan unlocked", notes:"Mualani's tribe (surfer/water folk). Water-related domain and crafting unlocks here.", rewards:"Primogems · Adv EXP · Mora · Tribe Reputation EXP", fandom:"https://genshin-impact.fandom.com/wiki/People_of_the_Springs" },
  { id:7, tier:2, chain:"tribal", name:"Tribal Chronicles — Masters of the Night-Wind", time:"20-30 min", region:"Sulfurous Veins · Masters of the Night-Wind territory", activate:"Tribal Chronicles menu. Liaison NPC in the tribe plaza.", prereqs:"Natlan unlocked", notes:"Ororon (Bidii) and Iansan's tribe. Spirit-related crafting / shop unlocks here.", rewards:"Primogems · Adv EXP · Mora · Tribe Reputation EXP", fandom:"https://genshin-impact.fandom.com/wiki/Masters_of_the_Night-Wind" },
  { id:8, tier:2, chain:"tribal", name:"Tribal Chronicles — Flower-Feather Clan", time:"20-30 min", region:"Atocpan · Flower-Feather Clan territory", activate:"Tribal Chronicles menu. Talk to the Flower-Feather liaison.", prereqs:"Natlan unlocked", notes:"Kachina and Chasca's tribe. Gliding-related rewards unlock here.", rewards:"Primogems · Adv EXP · Mora · Tribe Reputation EXP", fandom:"https://genshin-impact.fandom.com/wiki/Flower-Feather_Clan" },
  { id:9, tier:2, chain:"tribal", name:"Tribal Chronicles — Collective of Plenty", time:"20-30 min", region:"Tezcatepetonco Range · Collective of Plenty territory", activate:"Tribal Chronicles menu. Talk to the capybara-kin liaison.", prereqs:"Natlan unlocked", notes:"Varesa's tribe (the Capybara-kin). Plunge-related challenges unlock here.", rewards:"Primogems · Adv EXP · Mora · Tribe Reputation EXP", fandom:"https://genshin-impact.fandom.com/wiki/Collective_of_Plenty" },
  { id:10, tier:2, chain:"saurian", name:"Tepetlisaurus Hide-and-Seek", time:"15-25 min", region:"Natlan — various tribal areas", activate:"After naming the Tepetlisaur, the hide-and-seek mini-quest auto-starts.", prereqs:"Little One completed", notes:"Find your saurian in 4 hiding spots across Natlan. Light tutorial for Saurian companion abilities.", rewards:"Primogems · Adv EXP · Mora · Saurian companion familiarity unlocks", game8:"https://game8.co/games/Genshin-Impact/archives/409233" },
  { id:11, tier:2, chain:"saurian", name:"A Saurian Returns to the Nest", time:"15-25 min", region:"Toyac Springs area", activate:"Find the lost saurian baby NPC at a Toyac Springs camp.", prereqs:"Natlan accessible", notes:"Help reunite a saurian baby with its mother. Mostly dialogue + escort.", rewards:"Primogems · Adv EXP · Mora · Saurian-themed achievement", game8:"https://game8.co/games/Genshin-Impact/archives/331209" },
  { id:12, tier:2, chain:"saurian", name:"A Saurian Lover's Ordinary Days", time:"15-25 min", region:"Natlan — multiple tribal homes", activate:"Talk to the saurian researcher NPC who travels between tribes.", prereqs:"Natlan AQ Ch V Act II accessible", notes:"Multi-location chain visiting different saurian habitats. Light combat + observation objectives.", rewards:"Primogems · Adv EXP · Mora · saurian almanac entries", game8:"https://game8.co/games/Genshin-Impact/archives/470263" },

  { id:13, tier:3, chain:"story", name:"Mavuika — As the Blazing Sun", time:"45-60 min", region:"Natlan — Stadium of Sacred Flame", activate:"Story Quest menu. Spend 1 Story Key. Find Mavuika in the Stadium.", prereqs:"AR 40 + AQ Ch V Act V 'Incandescent Ode of Resurrection' + 1 Story Key (released v5.3)", notes:"Sol Invictus Chapter — Act I. Mavuika's first independent Story Quest. Time-limited bonus rewards if completed during the 'As the Blazing Sun' event window (now past for new players).", rewards:"60 Primogems · Adv EXP · Mora · Hero's Wit · Mavuika ascension materials", mora: 26925, heroWit: 3, game8:"https://game8.co/games/Genshin-Impact/archives/491942" },
  { id:14, tier:3, chain:"standalone", name:"Someday, We All Must Walk Alone", time:"30-45 min", region:"Sulfurous Veins area (Masters of the Night-Wind)", activate:"Find the marked NPC at the Sulfurous Veins.", prereqs:"Masters of the Night-Wind Tribal Chronicle started", notes:"Mid-length quest tied to Night-Wind spirit lore. Moderate combat + Night-Realm puzzles.", rewards:"Primogems · Adv EXP · Mora · Hero's Wit", game8:"https://game8.co/games/Genshin-Impact/archives/507447" },
  { id:15, tier:3, chain:"standalone", name:"Open Your Heart To Me", time:"30-45 min", region:"Natlan — multiple stops", activate:"Triggered by Natlan exploration progress + Saurian companion familiarity.", prereqs:"Natlan exploration + Saurian companion bond raised", notes:"Multi-step quest culminating in the 'Devoted to Eternal Serenity' achievement.", rewards:"Primogems · Achievement: Devoted to Eternal Serenity · Adv EXP · Mora", fandom:"https://genshin-impact.fandom.com/wiki/Open_Your_Heart_To_Me" },

  { id:16, tier:4, chain:"saurian", name:"In the Footsteps of the Chosen Dragons (10 quests)", time:"2-4 hours (full set, in any order)", region:"Natlan — across all tribal regions", activate:"Each of the 10 sub-quests auto-triggers at a specific saurian landmark.", prereqs:"Natlan + Saurian companion unlocked", notes:"10 standalone world quests, can be done in any order. Each highlights one of the saurian species you can ride. Critical for unlocking the full Saurian companion roster.", rewards:"Primogems (~20-40 each, ~300+ total) · Saurian companion gadgets · achievements", fandom:"https://genshin-impact.fandom.com/wiki/In_the_Footsteps_of_the_Chosen_of_Dragons" },
  { id:17, tier:4, chain:"standalone", name:"Revelations from the Past", time:"60-90 min", region:"Stadium of Sacred Flame + ancient ruins", activate:"Late AQ progression auto-triggers this chain.", prereqs:"AQ Ch V late progression", notes:"Long lore-heavy chain about pre-Cataclysm Natlan. Several boss-tier encounters.", rewards:"Primogems · Adv EXP · Mora · Hero's Wit · major lore unlocks", fandom:"https://genshin-impact.fandom.com/wiki/Revelations_from_the_Past" },
  { id:18, tier:4, chain:"standalone", name:"Pilgrimage of the Return of the Sacred Flame", time:"60-90 min", region:"Stadium of Sacred Flame", activate:"Late AQ progression auto-triggers this.", prereqs:"Natlan AQ Act IV+ progression", notes:"Ceremonial chain. Cinematic, dialogue-driven, sets up later character / story content.", rewards:"Primogems · Adv EXP · Mora · Hero's Wit · ceremonial unlocks", fandom:"https://genshin-impact.fandom.com/wiki/Pilgrimage_of_the_Return_of_the_Sacred_Flame_(Quest)" },
  { id:19, tier:4, chain:"standalone", name:"Natlan World Quests — Full Region", time:"15-25 hours (full ~48-quest set)", region:"All of Natlan", activate:"Natural progression as you explore. World quests pop on the map as you approach NPCs.", prereqs:"AR 30+ · Natlan unlocked · Statues of the Seven cycled", notes:"Natlan ships with ~48 permanent world quests per Game8 — this entry summarises the rest beyond what's individually listed above. Estimated 1,500-2,000 primogems for full clear.", rewards:"~1,500-2,000 Primogems · ~150,000+ Mora · Hero's Wit · MEO · Saurian companion gadgets · achievements", mora: 150000, heroWit: 20, game8:"https://game8.co/games/Genshin-Impact/archives/470500" },
  { id:20, tier:2, chain:"saurian", name:"Between Promise and Oblivion", time:"20-30 min", region:"Children of Echoes territory", activate:"Find the baby Tepetlisaur in the Children of Echoes area.", prereqs:"Children of Echoes territory accessible", notes:"Baby Tepetlisaurus caretaking chain. Quick completion with solid Mora reward for a Tier 2 quest.", rewards:"~32,000 Mora · 4 Hero's Wit · Adv EXP · Saurian companion lore", mora: 32000, heroWit: 4, fandom:"https://genshin-impact.fandom.com/wiki/Between_Promise_and_Oblivion" },
  { id:21, tier:2, chain:"tribal", name:"Hoarse Echoes", time:"20-30 min", region:"Children of Echoes territory", activate:"Talk to the tribal NPC in the Children of Echoes area after progressing tribal reputation.", prereqs:"Children of Echoes Tribal Chronicle started", notes:"Children of Echoes tribal quest with one of the higher per-quest Mora payouts in Natlan.", rewards:"32,625 Mora · 4 Hero's Wit · Adv EXP · Tribe Reputation EXP", mora: 32625, heroWit: 4, fandom:"https://genshin-impact.fandom.com/wiki/Hoarse_Echoes" },

  // ── TIER 1 — Under 5 min ──────────────────────────────────────
  { id:22, tier:1, chain:"standalone", name:"Toward Red-Hot Adventure!", time:"2 min", region:"Stadium of the Sacred Flame — Adventurer's Guild", activate:"Talk to Katheryne at the Natlan Adventurer's Guild.", prereqs:"Natlan accessible", notes:"Just talk to Katheryne. Unlocks Daily Commissions for Natlan. 21.5k Mora in 2 minutes is outstanding.", rewards:"21,500 Mora · Adv EXP", mora: 21500, game8:"https://game8.co/games/Genshin-Impact/archives/470503" },
  { id:23, tier:1, chain:"standalone", name:"Tepetli Dissonance", time:"3 min", region:"Children of Echoes — jewel shop", activate:"Talk to Imix near the jewel shop at Children of Echoes.", prereqs:"AQ Ch V Act I (Pilgrimage of the Return of the Sacred Flame)", notes:"Extremely short and straightforward. Tribal Chronicle-adjacent but NOT one of the six Tribal Chronicles.", rewards:"17,050 Mora · Adv EXP", mora: 17050, game8:"https://game8.co/games/Genshin-Impact/archives/409017" },
  { id:24, tier:1, chain:"hidden", name:"The Case of the Crafting Bench", time:"5 min", region:"Stadium of the Sacred Flame", activate:"Interact with a suspicious Crafting Bench in the Stadium of the Sacred Flame.", prereqs:"None (hidden quest)", notes:"Short hidden quest. Also gives 5 chests during the quest. Achievement: 'Whoa! What a Twist!'", rewards:"20,000 Mora · 2 Hero's Wit · 30 Primogems · 3 MEO", mora: 20000, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/470590" },
  { id:25, tier:1, chain:"footsteps", name:"To Wish Upon a Star", time:"5 min", region:"Coatepec Mountain", activate:"Talk to Orqo in Coatepec Mountain. TP northeast of Ancestral Temple, head east to find a kid near a big hole.", prereqs:"None", notes:"Collect star shards by indwelling a Tepetlisaurus. Fun and quick. 26.5k Mora in 5 min.", rewards:"26,500 Mora · 20 Primogems", mora: 26500, game8:"https://game8.co/games/Genshin-Impact/archives/470545" },
  { id:26, tier:1, chain:"footsteps", name:"Special Friends", time:"5 min", region:"Near Scions of the Canopy", activate:"Auto-triggers when approaching the area.", prereqs:"Lost in the Woods completed", notes:"Part of In the Footsteps chain. Report to Wactana, receive a small wooden alpaca.", rewards:"26,500 Mora · 20 Primogems", mora: 26500, game8:"https://game8.co/games/Genshin-Impact/archives/406232" },
  { id:27, tier:1, chain:"footsteps", name:"Lies and Promises", time:"5 min", region:"Teticpac Peak (underground, SE of Scions of the Canopy)", activate:"Find a Strange Yumkasaurus blocking a Luxurious Chest in the cave system. Indwell a Yumkasaurus nearby to communicate.", prereqs:"Lost in the Woods completed", notes:"Hidden quest. Feed the Yumkasaurus Raw Meat afterward for 'A Final Kindness' achievement.", rewards:"25,000 Mora · 20 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/413658" },
  { id:28, tier:1, chain:"footsteps", name:"Feeling Like Fish Today!", time:"5 min", region:"Teticpac Peak — southeast dock", activate:"Go to the small dock at the SE side of Teticpac Peak. Your Saurian companion wanders to observe the water.", prereqs:"Lost in the Woods completed", notes:"Clean up water, swim as Koholasaur, cook fish. Achievement: '...And Thank for All the Fish!'", rewards:"25,000 Mora · 20 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/386413" },
  { id:29, tier:1, chain:"footsteps", name:"Lights, Kamera, Action!", time:"5 min", region:"Coatepec Mountain — cliff top", activate:"Find a camera on a cliff. Use Statue of the Seven in Children of Echoes, embody a Tepetlisaur via Spiritsconce, use Molten Fissure to reach the cliff.", prereqs:"Lost in the Woods completed", notes:"Fun movie-making quest. Also gives Teapot decoration.", rewards:"25,000 Mora · 20 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/387766" },

  // ── TIER 2 — 5-15 min ─────────────────────────────────────────
  { id:30, tier:2, chain:"footsteps", name:"Charge Forward! Go, Go, Go!", time:"5-10 min", region:"Tezcatepetonco Range — floating balloon house", activate:"Land on the floating balloon house SW of the southernmost TP in Tezcatepetonco Range. Blow horns left-right-left-right.", prereqs:"Lost in the Woods completed", notes:"Become a Qucusaurus and fly to collect gold coins / aerial rings. Aim for SS Rank. Prerequisite for Every Aspect of a Warrior.", rewards:"20,000 Mora · 20 Primogems", mora: 20000, fandom:"https://genshin-impact.fandom.com/wiki/Charge_Forward!_Go,_Go,_Go!" },
  { id:31, tier:2, chain:"standalone", name:"Molting Season", time:"10 min", region:"Flower-Feather Clan area", activate:"Approach the camp with two Angry Saurian Traffickers SE of Flower-Feather Clan main village.", prereqs:"None", notes:"Prerequisite for Every Aspect of a Warrior. No prior quest required.", rewards:"22,500 Mora · 2 Hero's Wit · 30 Primogems", mora: 22500, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/305089" },
  { id:32, tier:2, chain:"footsteps", name:"Weighty Wings", time:"10 min", region:"NE of Teticpac Peak", activate:"Approach suspicious warriors NE of Teticpac Peak. Defeat them, check on injured Saurian.", prereqs:"Lost in the Woods completed", notes:"Heal an injured Qucusaurus using Embercore Flowers (Cryo attacks to open petals).", rewards:"35,000 Mora · 30 Primogems", mora: 35000, game8:"https://game8.co/games/Genshin-Impact/archives/394480" },
  { id:33, tier:2, chain:"footsteps", name:"Treasures and Collectors", time:"10 min", region:"Basin of Unnumbered Flames (NW of Scions of the Canopy)", activate:"Talk to Quipia at an excavation site in the Basin of Unnumbered Flames.", prereqs:"Lost in the Woods completed", notes:"Explore underground with your Tepetlisaur. Also gives Secret Source Ball Mechanism for rest area.", rewards:"35,000 Mora · 30 Primogems", mora: 35000, game8:"https://game8.co/games/Genshin-Impact/archives/397178" },
  { id:34, tier:2, chain:"footsteps", name:"Sauro-Vet's Dilemma", time:"10 min", region:"Flower-Feather Clan — east side", activate:"Go to the east side of Flower-Feather Clan settlement.", prereqs:"Lost in the Woods completed", notes:"Tame an angry Qucusaur. Achievement: 'It's Not Much, But It's A Start...'", rewards:"25,000 Mora · 30 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/408485" },
  { id:35, tier:2, chain:"standalone", name:"Ripe for Trouble", time:"10-15 min", region:"Tequemecan Valley — Flamegranate Tree Roots", activate:"Get the Green-Edged Paper Slip from Scions of the Canopy area in Coatepec Mountain, then talk to Poca at the cave entrance.", prereqs:"Green-Edged Paper Slip obtained", notes:"Cave exploration with Coilgrass Sigils. Talk to Poca AFTER completion for extra 20k Mora.", rewards:"33,000 Mora · 2 Hero's Wit · 40 Primogems", mora: 33000, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/470491" },
  { id:36, tier:2, chain:"footsteps", name:"Gifts and Gifts in Return", time:"10-15 min", region:"Children of Echoes — Tepeacac Rise waterfall", activate:"Find pillars at the foot of a waterfall SW of Tepeacac Rise. Enter the Rest Area.", prereqs:"Lost in the Woods completed", notes:"Follow your Saurian, help Master Kulahaw collect gems as Yumkasaurus. Requires 2-day in-game time skip. Achievement: 'Maybe This is a Good Place to Camp?'", rewards:"25,000 Mora · 30 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/470305" },
  { id:37, tier:2, chain:"footsteps", name:"Stones, Coconuts, and Saurian Traffickers", time:"10-15 min", region:"Natlan overworld", activate:"Part of In the Footsteps chain.", prereqs:"Lost in the Woods completed", notes:"Defeat saurian traffickers. Achievement: 'Cat Food for Prawn Guns.' Serenitea Pot furniture reward.", rewards:"25,000 Mora · 30 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/381311" },
  { id:38, tier:2, chain:"footsteps", name:"Friends of Fire and Water", time:"10-15 min", region:"Masters of the Night-Wind — SW shores", activate:"Go to shores SW of Masters of the Night-Wind clan area. Find dragon traffickers.", prereqs:"Lost in the Woods completed", notes:"Defeat traffickers, free caged animals. Achievement: 'Would Fontaine Beasts Eat Natlan Fish?'", rewards:"25,000 Mora · 30 Primogems", mora: 25000, game8:"https://game8.co/games/Genshin-Impact/archives/432237" },
  { id:39, tier:2, chain:"standalone", name:"Every Aspect of a Warrior", time:"10 min", region:"Tezcatepetonco Range", activate:"Auto-unlocks after completing Molting Season, Charge Forward! Go Go Go!, and A Saurian Returns to the Nest.", prereqs:"All 3 prerequisite quests completed", notes:"Hidden quest. Final step is a flying challenge. Achievement: 'Glory of the Chase, Or Its Meaning...'", rewards:"35,000 Mora · 30 Primogems", mora: 35000, game8:"https://game8.co/games/Genshin-Impact/archives/315981" },

  // ── TIER 2 — 15-20 min ────────────────────────────────────────
  { id:40, tier:2, chain:"standalone", name:"Stride on Rainbows, Split the Waves", time:"15-20 min", region:"Toyac Springs / Natlan coast", activate:"Find the quest in the Toyac Springs area. Involves surfing/Rongo training.", prereqs:"None", notes:"Fun surfing quest. Timed challenge (collect 25 Pyro Particles in 600 seconds).", rewards:"30,000 Mora · 2 Hero's Wit · 40 Primogems · 3 MEO", mora: 30000, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/470344" },
  { id:41, tier:2, chain:"standalone", name:"Tracer No Tracing", time:"15 min", region:"Underground tunnel at Ameyalco Waters", activate:"After Lost in the Woods, find Chikya in an underground tunnel at Ameyalco Waters.", prereqs:"Lost in the Woods completed", notes:"First half of Tale of Dreams Plucked From Fire. Continues into Seeker No Finding.", rewards:"25,000 Mora · 2 Hero's Wit · 30 Primogems", mora: 25000, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/470197" },
  { id:42, tier:2, chain:"standalone", name:"Seeker No Finding", time:"15 min", region:"Ameyalco Waters", activate:"Continues automatically after Tracer No Tracing.", prereqs:"Tracer No Tracing completed", notes:"Second half of Tale of Dreams Plucked From Fire. Completes the chain.", rewards:"25,000 Mora · 2 Hero's Wit · 40 Primogems", mora: 25000, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/470229" },

  // ── TIER 3 — 15-30 min ────────────────────────────────────────
  { id:43, tier:3, chain:"standalone", name:"Beneath the Crystal Rock", time:"15 min", region:"Tequemecan Valley", activate:"Find Titu in Tequemecan Valley. Auto-unlocks after AQ Pilgrimage subquest.", prereqs:"AQ Ch V Pilgrimage subquest", notes:"First part of Shadows of the Mountains chain. 5 Hero's Wit is the highest single-quest HW in Natlan. Explore beneath the Sulfurous Veins.", rewards:"34,000 Mora · 5 Hero's Wit · 50 Primogems", mora: 34000, heroWit: 5, game8:"https://game8.co/games/Genshin-Impact/archives/470231" },
  { id:44, tier:3, chain:"standalone", name:"Peace to the Slumbering", time:"15 min", region:"Sulfurous Veins", activate:"Continues after Beneath the Crystal Rock.", prereqs:"Beneath the Crystal Rock completed", notes:"Second part of Shadows of the Mountains. Combined with part 1: 57.5k Mora + 7 HW + 90 Primogems in ~30 min.", rewards:"23,500 Mora · 2 Hero's Wit · 40 Primogems", mora: 23500, heroWit: 2, game8:"https://game8.co/games/Genshin-Impact/archives/470270" },

  // ───────── EASYBREEZE HOLIDAY RESORT (v5.8) ─────────
  { id:45, tier:1, chain:"easybreeze", name:"Encounters Always Happen on a Holiday", time:"5 min", region:"Easybreeze Holiday Resort — Easybreeze Market", activate:"Approach Ifa and Ororon near the water south of Easybreeze Market.", prereqs:"Sunspray Summer Resort chain — Part 2 completed", notes:"Watch a fishing-competition cutscene. Awards a Gift Egg (random Natlan dish). Leads to All Good Reunions Follow a Search after daily reset.", rewards:"20 Primogems · Gift Egg", game8:"https://game8.co/games/Genshin-Impact/archives/540200" },
  { id:46, tier:1, chain:"easybreeze", name:"All Good Reunions Follow a Search", time:"5 min", region:"Easybreeze Holiday Resort — NW of Easybreeze Market", activate:"Approach Ifa and Ororon at the building NW of Easybreeze Market.", prereqs:"Encounters Always Happen on a Holiday + 1 daily reset", notes:"Hide and seek game with Ifa and Ororon. Very short.", rewards:"20 Primogems · Gift Egg", game8:"https://game8.co/games/Genshin-Impact/archives/540230" },
  { id:47, tier:2, chain:"easybreeze", name:"Dreamy Paititi", time:"10-15 min", region:"Easybreeze Holiday Resort — Tete Isle", activate:"Cleanse strange flowers near Tete Isle.", prereqs:"Easybreeze Holiday Resort accessible", notes:"Cleansing puzzle quest. Awards an Exquisite Chest plus hidden achievement.", rewards:"40 Primogems · Exquisite Chest · hidden achievement", game8:"https://game8.co/games/Genshin-Impact/archives/540167" },
  { id:48, tier:2, chain:"easybreeze", name:"Traces of Chroma", time:"15-20 min", region:"Easybreeze Holiday Resort", activate:"Triggered by exploration of Easybreeze Holiday Resort.", prereqs:"Sunspray Summer Resort story chain progressed", notes:"Multi-step exploration puzzle. Awards 2 Exquisite + 1 Precious Chest.", rewards:"40 Primogems · 2 Exquisite Chests · 1 Precious Chest", game8:"https://game8.co/games/Genshin-Impact/archives/540180" },
  { id:49, tier:2, chain:"easybreeze", name:"Shine On, Pipilpan Idol!", time:"15-20 min", region:"Easybreeze Holiday Resort", activate:"Find the Pipilpan idol quest start point in Easybreeze area.", prereqs:"Easybreeze Holiday Resort accessible", notes:"Idol-light puzzle quest. Awards chests + primogems.", rewards:"40 Primogems · chests", game8:"https://gamewith.net/genshin-impact/article/show/22408" },
  { id:50, tier:3, chain:"easybreeze", name:"The Last Survivor of Tenochtzitoc", time:"20-25 min", region:"Easybreeze Holiday Resort — south of Wavey Bay", activate:"Battle the Battle-Hardened Pipilpan Doll (Local Legend) south of Wavey Bay.", prereqs:"Easybreeze Holiday Resort accessible · combat-ready party", notes:"Local Legend boss fight. Essential for Mare Jivari lore. Awards a Luxurious Chest among 4 chests.", rewards:"50 Primogems · Luxurious Chest · 3 additional chests", game8:"https://game8.co/games/Genshin-Impact/archives/541361" },
  { id:51, tier:3, chain:"easybreeze", name:"An Easy-Breezy Natlan in an Easy-Breezy Summer! (Main Chain)", time:"45-60 min (4 sequential parts)", region:"Easybreeze Holiday Resort — across the region", activate:"Auto-triggers in the Holiday Resort after entering during the 5.8 update.", prereqs:"Natlan accessible · 5.8 content available", notes:"4-part Sunspray Summer Resort main chain. Unlocks the other Easybreeze World Quests as you progress. Largest payout in the Easybreeze region.", rewards:"~100 Primogems · Adv EXP · Mora · Hero's Wit · Sunspray exploration unlocks", mora: 60000, heroWit: 6, fandom:"https://genshin-impact.fandom.com/wiki/An_Easy-Breezy_Natlan_in_an_Easy-Breezy_Summer!" },
];

const orderNote = [
  { step:1, text:"Quick wins: Natlan! A New Adventure (intro) → Lost in the Woods → Little One (naming) → Tepetlisaurus Hide-and-Seek. All four are short and chain together — they unlock the Saurian companion system that gates a lot of later Natlan content." },
  { step:2, text:"Tribal Chronicles are Natlan's reputation-style backbone (one per tribe). Pick them up as you visit each tribe's home; each gives crafting / domain / mobility unlocks beyond the primogems." },
  { step:3, text:"Saurian companion line: A Saurian Returns to the Nest → A Saurian Lover's Ordinary Days → In the Footsteps of the Chosen Dragons (10 sub-quests, any order). Tier 4 entry alone is worth ~300 primo and unlocks every ride-able dragon." },
  { step:4, text:"Mavuika's Story Quest is gated by AQ Ch V Act V (Incandescent Ode of Resurrection) — finish the main story before spending a Story Key on it." },
  { step:5, text:"Pilgrimage / Revelations are late-AQ chains. Don't go for them before completing Acts IV / V of Chapter V." },
  { step:6, text:"This tracker enumerates the well-documented chains. The 'Natlan World Quests — Full Region' Tier 4 entry covers the remaining ~30 short side-stories per tribe that aren't individually listed." },
  { step:7, text:"Ultra-fast Mora sweep: Toward Red-Hot Adventure (2 min, 21.5k), Tepetli Dissonance (3 min, 17k), The Case of the Crafting Bench (5 min, 20k+2HW). All in the Stadium/Children of Echoes area — combine in one 10-min session for ~58.5k Mora." },
  { step:8, text:"Footsteps chain sweep: after Lost in the Woods, the 10 individual In the Footsteps sub-quests are each 5-15 min and give 25-35k Mora each. Do them as you explore — total ~300k Mora across all 10." },
  { step:9, text:"Best Hero's Wit: Beneath the Crystal Rock (5 HW, 15 min) → Peace to the Slumbering (2 HW, 15 min). Combined 57.5k Mora + 7 HW in 30 min is the best HW farming chain in Natlan." },
];

const config = {
  title: "Natlan World Quests",
  subtitleLabel: "Tribal Chronicles · Story Quests · Hangouts — primogems, Mora & Hero's Wit",
  logoEmoji: "🌋",
  completeEmoji: "🌋✨",
  completeTitle: "ALL NATLAN QUESTS COMPLETE",
  completeMessage: "The Sacred Flame remembers your tribe, Traveler.",
  storageKey: "natlan-quest-tracker-v1",
  tiers, chainTags, quests, orderNote,
  theme: {
    pageBg:           "linear-gradient(160deg,#1a0703 0%,#3a1308 40%,#552010 100%)",
    headerBg:         "rgba(15,4,2,0.97)",
    pattern1:         "rgba(254,202,87,0.06)",
    pattern2:         "rgba(220,38,38,0.06)",
    cardBg:           "linear-gradient(135deg,rgba(40,15,8,0.92),rgba(28,8,4,0.92))",
    logoBg:           "linear-gradient(135deg,#dc2626,#7c1d1d)",
    titleGradient:    "linear-gradient(135deg,#fff7ed 0%,#fb923c 50%,#9a3412 100%)",
    progressGradient: "linear-gradient(90deg,#7c2d12,#dc2626,#fb923c)",
    textPrimary:      "#ffedd5",
    textBright:       "#fff7ed",
    textRgb:          [255, 237, 213],
    accent:           "#fb923c",
    accentRgb:        [251, 146, 60],
  },
};

export default function NatlanQuests() {
  return <RegionQuestTracker config={config} />;
}
